set(MonorepoPackages
    streamr-json
    streamr-logger
    streamr-eventemitter
    streamr-utils
    streamr-proto-rpc
    streamr-dht
    streamr-trackerless-network
    streamr-libstreamrproxyclient
)
