// Generated by the protocol buffer streamr pluging. DO NOT EDIT!
// Generated from protobuf file "packages/dht/protos/DhtRpc.proto"

#ifndef STREAMR_PROTORPC_DHTRPC_SERVER_PB_H
#define STREAMR_PROTORPC_DHTRPC_SERVER_PB_H

#include "DhtRpc.pb.h" // NOLINT
#include <folly/coro/Task.h>

namespace dht {
template <typename CallContextType>
class DhtNodeRpc {
public:
   virtual ~DhtNodeRpc() = default;
   virtual ClosestPeersResponse getClosestPeers(const ClosestPeersRequest& request, const CallContextType& callContext) = 0;
   virtual ClosestRingPeersResponse getClosestRingPeers(const ClosestRingPeersRequest& request, const CallContextType& callContext) = 0;
   virtual PingResponse ping(const PingRequest& request, const CallContextType& callContext) = 0;
   virtual void leaveNotice(const LeaveNotice& request, const CallContextType& callContext) = 0;
}; // class DhtNodeRpc
template <typename CallContextType>
class RouterRpc {
public:
   virtual ~RouterRpc() = default;
   virtual RouteMessageAck routeMessage(const RouteMessageWrapper& request, const CallContextType& callContext) = 0;
   virtual RouteMessageAck forwardMessage(const RouteMessageWrapper& request, const CallContextType& callContext) = 0;
}; // class RouterRpc
template <typename CallContextType>
class RecursiveOperationRpc {
public:
   virtual ~RecursiveOperationRpc() = default;
   virtual RouteMessageAck routeRequest(const RouteMessageWrapper& request, const CallContextType& callContext) = 0;
}; // class RecursiveOperationRpc
template <typename CallContextType>
class StoreRpc {
public:
   virtual ~StoreRpc() = default;
   virtual StoreDataResponse storeData(const StoreDataRequest& request, const CallContextType& callContext) = 0;
   virtual void replicateData(const ReplicateDataRequest& request, const CallContextType& callContext) = 0;
}; // class StoreRpc
template <typename CallContextType>
class RecursiveOperationSessionRpc {
public:
   virtual ~RecursiveOperationSessionRpc() = default;
   virtual void sendResponse(const RecursiveOperationResponse& request, const CallContextType& callContext) = 0;
}; // class RecursiveOperationSessionRpc
template <typename CallContextType>
class WebsocketClientConnectorRpc {
public:
   virtual ~WebsocketClientConnectorRpc() = default;
   virtual void requestConnection(const WebsocketConnectionRequest& request, const CallContextType& callContext) = 0;
}; // class WebsocketClientConnectorRpc
template <typename CallContextType>
class WebrtcConnectorRpc {
public:
   virtual ~WebrtcConnectorRpc() = default;
   virtual void requestConnection(const WebrtcConnectionRequest& request, const CallContextType& callContext) = 0;
   virtual void rtcOffer(const RtcOffer& request, const CallContextType& callContext) = 0;
   virtual void rtcAnswer(const RtcAnswer& request, const CallContextType& callContext) = 0;
   virtual void iceCandidate(const IceCandidate& request, const CallContextType& callContext) = 0;
}; // class WebrtcConnectorRpc
template <typename CallContextType>
class ConnectionLockRpc {
public:
   virtual ~ConnectionLockRpc() = default;
   virtual LockResponse lockRequest(const LockRequest& request, const CallContextType& callContext) = 0;
   virtual void unlockRequest(const UnlockRequest& request, const CallContextType& callContext) = 0;
   virtual void gracefulDisconnect(const DisconnectNotice& request, const CallContextType& callContext) = 0;
}; // class ConnectionLockRpc
template <typename CallContextType>
class ExternalApiRpc {
public:
   virtual ~ExternalApiRpc() = default;
   virtual ExternalFetchDataResponse externalFetchData(const ExternalFetchDataRequest& request, const CallContextType& callContext) = 0;
   virtual ExternalStoreDataResponse externalStoreData(const ExternalStoreDataRequest& request, const CallContextType& callContext) = 0;
}; // class ExternalApiRpc
}; // namespace dht

#endif // STREAMR_PROTORPC_DHTRPC_SERVER_PB_H

