// Generated by the protocol buffer streamr pluging. DO NOT EDIT!
// Generated from protobuf file "HelloRpc.proto"

#ifndef STREAMR_PROTORPC_HELLORPC_SERVER_PB_H
#define STREAMR_PROTORPC_HELLORPC_SERVER_PB_H

#include "HelloRpc.pb.h" // NOLINT
#include <folly/experimental/coro/Task.h>
#include "streamr-proto-rpc/ProtoCallContext.hpp" // NOLINT
using streamr::protorpc::ProtoCallContext;


namespace streamr::protorpc {
class HelloRpcService {
public:
   virtual ~HelloRpcService() = default;
   virtual HelloResponse sayHello(const HelloRequest& request, const ProtoCallContext& callContext) = 0;
}; // class HelloRpcService
}; // namespace streamr::protorpc

#endif // STREAMR_PROTORPC_HELLORPC_SERVER_PB_H

