// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: RoutedHelloRpc.proto
// Protobuf C++ Version: 6.33.4

#ifndef RoutedHelloRpc_2eproto_2epb_2eh
#define RoutedHelloRpc_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_RoutedHelloRpc_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_RoutedHelloRpc_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_RoutedHelloRpc_2eproto;
}  // extern "C"
class RoutedHelloRequest;
struct RoutedHelloRequestDefaultTypeInternal;
extern RoutedHelloRequestDefaultTypeInternal _RoutedHelloRequest_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull RoutedHelloRequest_class_data_;
class RoutedHelloResponse;
struct RoutedHelloResponseDefaultTypeInternal;
extern RoutedHelloResponseDefaultTypeInternal _RoutedHelloResponse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull RoutedHelloResponse_class_data_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class RoutedHelloResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:RoutedHelloResponse) */ {
 public:
  inline RoutedHelloResponse() : RoutedHelloResponse(nullptr) {}
  ~RoutedHelloResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(RoutedHelloResponse* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(RoutedHelloResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR RoutedHelloResponse(::google::protobuf::internal::ConstantInitialized);

  inline RoutedHelloResponse(const RoutedHelloResponse& from) : RoutedHelloResponse(nullptr, from) {}
  inline RoutedHelloResponse(RoutedHelloResponse&& from) noexcept
      : RoutedHelloResponse(nullptr, ::std::move(from)) {}
  inline RoutedHelloResponse& operator=(const RoutedHelloResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline RoutedHelloResponse& operator=(RoutedHelloResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RoutedHelloResponse& default_instance() {
    return *reinterpret_cast<const RoutedHelloResponse*>(
        &_RoutedHelloResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(RoutedHelloResponse& a, RoutedHelloResponse& b) { a.Swap(&b); }
  inline void Swap(RoutedHelloResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RoutedHelloResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RoutedHelloResponse* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<RoutedHelloResponse>(arena);
  }
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(RoutedHelloResponse* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "RoutedHelloResponse"; }

  explicit RoutedHelloResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  RoutedHelloResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const RoutedHelloResponse& from);
  RoutedHelloResponse(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, RoutedHelloResponse&& from) noexcept
      : RoutedHelloResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kGreetingFieldNumber = 1,
  };
  // string greeting = 1;
  void clear_greeting() ;
  const ::std::string& greeting() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_greeting(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_greeting();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_greeting();
  void set_allocated_greeting(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_greeting() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_greeting(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_greeting();

  public:
  // @@protoc_insertion_point(class_scope:RoutedHelloResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 36,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const RoutedHelloResponse& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr greeting_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_RoutedHelloRpc_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull RoutedHelloResponse_class_data_;
// -------------------------------------------------------------------

class RoutedHelloRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:RoutedHelloRequest) */ {
 public:
  inline RoutedHelloRequest() : RoutedHelloRequest(nullptr) {}
  ~RoutedHelloRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(RoutedHelloRequest* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(RoutedHelloRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR RoutedHelloRequest(::google::protobuf::internal::ConstantInitialized);

  inline RoutedHelloRequest(const RoutedHelloRequest& from) : RoutedHelloRequest(nullptr, from) {}
  inline RoutedHelloRequest(RoutedHelloRequest&& from) noexcept
      : RoutedHelloRequest(nullptr, ::std::move(from)) {}
  inline RoutedHelloRequest& operator=(const RoutedHelloRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline RoutedHelloRequest& operator=(RoutedHelloRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RoutedHelloRequest& default_instance() {
    return *reinterpret_cast<const RoutedHelloRequest*>(
        &_RoutedHelloRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(RoutedHelloRequest& a, RoutedHelloRequest& b) { a.Swap(&b); }
  inline void Swap(RoutedHelloRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RoutedHelloRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RoutedHelloRequest* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<RoutedHelloRequest>(arena);
  }
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(RoutedHelloRequest* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "RoutedHelloRequest"; }

  explicit RoutedHelloRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  RoutedHelloRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const RoutedHelloRequest& from);
  RoutedHelloRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, RoutedHelloRequest&& from) noexcept
      : RoutedHelloRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kMyNameFieldNumber = 1,
  };
  // string myName = 1;
  void clear_myname() ;
  const ::std::string& myname() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_myname(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_myname();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_myname();
  void set_allocated_myname(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_myname() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_myname(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_myname();

  public:
  // @@protoc_insertion_point(class_scope:RoutedHelloRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 33,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const RoutedHelloRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr myname_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_RoutedHelloRpc_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull RoutedHelloRequest_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// RoutedHelloRequest

// string myName = 1;
inline void RoutedHelloRequest::clear_myname() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.myname_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& RoutedHelloRequest::myname() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:RoutedHelloRequest.myName)
  return _internal_myname();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void RoutedHelloRequest::set_myname(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.myname_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:RoutedHelloRequest.myName)
}
inline ::std::string* PROTOBUF_NONNULL RoutedHelloRequest::mutable_myname()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_myname();
  // @@protoc_insertion_point(field_mutable:RoutedHelloRequest.myName)
  return _s;
}
inline const ::std::string& RoutedHelloRequest::_internal_myname() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.myname_.Get();
}
inline void RoutedHelloRequest::_internal_set_myname(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.myname_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL RoutedHelloRequest::_internal_mutable_myname() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.myname_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE RoutedHelloRequest::release_myname() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:RoutedHelloRequest.myName)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.myname_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.myname_.Set("", GetArena());
  }
  return released;
}
inline void RoutedHelloRequest::set_allocated_myname(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.myname_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.myname_.IsDefault()) {
    _impl_.myname_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:RoutedHelloRequest.myName)
}

// -------------------------------------------------------------------

// RoutedHelloResponse

// string greeting = 1;
inline void RoutedHelloResponse::clear_greeting() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.greeting_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& RoutedHelloResponse::greeting() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:RoutedHelloResponse.greeting)
  return _internal_greeting();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void RoutedHelloResponse::set_greeting(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.greeting_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:RoutedHelloResponse.greeting)
}
inline ::std::string* PROTOBUF_NONNULL RoutedHelloResponse::mutable_greeting()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_greeting();
  // @@protoc_insertion_point(field_mutable:RoutedHelloResponse.greeting)
  return _s;
}
inline const ::std::string& RoutedHelloResponse::_internal_greeting() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.greeting_.Get();
}
inline void RoutedHelloResponse::_internal_set_greeting(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.greeting_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL RoutedHelloResponse::_internal_mutable_greeting() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.greeting_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE RoutedHelloResponse::release_greeting() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:RoutedHelloResponse.greeting)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.greeting_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.greeting_.Set("", GetArena());
  }
  return released;
}
inline void RoutedHelloResponse::set_allocated_greeting(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.greeting_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.greeting_.IsDefault()) {
    _impl_.greeting_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:RoutedHelloResponse.greeting)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // RoutedHelloRpc_2eproto_2epb_2eh
