// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RoutedHelloRpc.proto

#include "RoutedHelloRpc.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;

inline constexpr RoutedHelloResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : greeting_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR RoutedHelloResponse::RoutedHelloResponse(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct RoutedHelloResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RoutedHelloResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RoutedHelloResponseDefaultTypeInternal() {}
  union {
    RoutedHelloResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RoutedHelloResponseDefaultTypeInternal _RoutedHelloResponse_default_instance_;

inline constexpr RoutedHelloRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : myname_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR RoutedHelloRequest::RoutedHelloRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct RoutedHelloRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RoutedHelloRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RoutedHelloRequestDefaultTypeInternal() {}
  union {
    RoutedHelloRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RoutedHelloRequestDefaultTypeInternal _RoutedHelloRequest_default_instance_;
static ::_pb::Metadata file_level_metadata_RoutedHelloRpc_2eproto[2];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_RoutedHelloRpc_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_RoutedHelloRpc_2eproto = nullptr;
const ::uint32_t TableStruct_RoutedHelloRpc_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::RoutedHelloRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::RoutedHelloRequest, _impl_.myname_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::RoutedHelloResponse, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::RoutedHelloResponse, _impl_.greeting_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::RoutedHelloRequest)},
        {9, -1, -1, sizeof(::RoutedHelloResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::_RoutedHelloRequest_default_instance_._instance,
    &::_RoutedHelloResponse_default_instance_._instance,
};
const char descriptor_table_protodef_RoutedHelloRpc_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\024RoutedHelloRpc.proto\"$\n\022RoutedHelloReq"
    "uest\022\016\n\006myName\030\001 \001(\t\"\'\n\023RoutedHelloRespo"
    "nse\022\020\n\010greeting\030\001 \001(\t2N\n\025RoutedHelloRpcS"
    "ervice\0225\n\010sayHello\022\023.RoutedHelloRequest\032"
    "\024.RoutedHelloResponseB\002H\002b\006proto3"
};
static ::absl::once_flag descriptor_table_RoutedHelloRpc_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_RoutedHelloRpc_2eproto = {
    false,
    false,
    193,
    descriptor_table_protodef_RoutedHelloRpc_2eproto,
    "RoutedHelloRpc.proto",
    &descriptor_table_RoutedHelloRpc_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_RoutedHelloRpc_2eproto::offsets,
    file_level_metadata_RoutedHelloRpc_2eproto,
    file_level_enum_descriptors_RoutedHelloRpc_2eproto,
    file_level_service_descriptors_RoutedHelloRpc_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_RoutedHelloRpc_2eproto_getter() {
  return &descriptor_table_RoutedHelloRpc_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_RoutedHelloRpc_2eproto(&descriptor_table_RoutedHelloRpc_2eproto);
// ===================================================================

class RoutedHelloRequest::_Internal {
 public:
};

RoutedHelloRequest::RoutedHelloRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:RoutedHelloRequest)
}
inline PROTOBUF_NDEBUG_INLINE RoutedHelloRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : myname_(arena, from.myname_),
        _cached_size_{0} {}

RoutedHelloRequest::RoutedHelloRequest(
    ::google::protobuf::Arena* arena,
    const RoutedHelloRequest& from)
    : ::google::protobuf::Message(arena) {
  RoutedHelloRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:RoutedHelloRequest)
}
inline PROTOBUF_NDEBUG_INLINE RoutedHelloRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : myname_(arena),
        _cached_size_{0} {}

inline void RoutedHelloRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
RoutedHelloRequest::~RoutedHelloRequest() {
  // @@protoc_insertion_point(destructor:RoutedHelloRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void RoutedHelloRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.myname_.Destroy();
  _impl_.~Impl_();
}

::_pbi::CachedSize* RoutedHelloRequest::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void RoutedHelloRequest::InternalSwap(RoutedHelloRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata RoutedHelloRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_RoutedHelloRpc_2eproto_getter, &descriptor_table_RoutedHelloRpc_2eproto_once,
      file_level_metadata_RoutedHelloRpc_2eproto[0]);
}
// ===================================================================

class RoutedHelloResponse::_Internal {
 public:
};

RoutedHelloResponse::RoutedHelloResponse(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:RoutedHelloResponse)
}
inline PROTOBUF_NDEBUG_INLINE RoutedHelloResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : greeting_(arena, from.greeting_),
        _cached_size_{0} {}

RoutedHelloResponse::RoutedHelloResponse(
    ::google::protobuf::Arena* arena,
    const RoutedHelloResponse& from)
    : ::google::protobuf::Message(arena) {
  RoutedHelloResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:RoutedHelloResponse)
}
inline PROTOBUF_NDEBUG_INLINE RoutedHelloResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : greeting_(arena),
        _cached_size_{0} {}

inline void RoutedHelloResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
RoutedHelloResponse::~RoutedHelloResponse() {
  // @@protoc_insertion_point(destructor:RoutedHelloResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void RoutedHelloResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.greeting_.Destroy();
  _impl_.~Impl_();
}

::_pbi::CachedSize* RoutedHelloResponse::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void RoutedHelloResponse::InternalSwap(RoutedHelloResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata RoutedHelloResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_RoutedHelloRpc_2eproto_getter, &descriptor_table_RoutedHelloRpc_2eproto_once,
      file_level_metadata_RoutedHelloRpc_2eproto[1]);
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
