// generated by the protocol buffer streamr pluging. DO NOT EDIT!
// generated from protobuf file "RoutedHelloRpc.proto"

#ifndef STREAMR_PROTORPC_ROUTEDHELLORPC_CLIENT_PB_H
#define STREAMR_PROTORPC_ROUTEDHELLORPC_CLIENT_PB_H

#include <folly/experimental/coro/Task.h>
#include "RoutedHelloRpc.pb.h" // NOLINT
#include "streamr-proto-rpc/ProtoCallContext.hpp"
#include "streamr-proto-rpc/RpcCommunicator.hpp"


namespace streamr::protorpc {
using streamr::protorpc::RpcCommunicator;
using streamr::protorpc::ProtoCallContext;
template <typename CallContextType>
class RoutedHelloRpcServiceClient {
private:
RpcCommunicator<CallContextType>& communicator;
public:
    explicit RoutedHelloRpcServiceClient(RpcCommunicator<CallContextType>& communicator) : communicator(communicator) {}
    folly::coro::Task<RoutedHelloResponse> sayHello(RoutedHelloRequest&& request, CallContextType&& callContext) {
        return communicator.template request<RoutedHelloResponse, RoutedHelloRequest>("sayHello", std::move(request), std::move(callContext));
    }
}; // class RoutedHelloRpcServiceClient
}; // namespace streamr::protorpc

#endif // STREAMR_PROTORPC_ROUTEDHELLORPC_CLIENT_PB_H

