// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: RoutedHelloRpc.proto
// Protobuf C++ Version: 6.33.4

#include "RoutedHelloRpc.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr RoutedHelloResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        greeting_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR RoutedHelloResponse::RoutedHelloResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(RoutedHelloResponse_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct RoutedHelloResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RoutedHelloResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RoutedHelloResponseDefaultTypeInternal() {}
  union {
    RoutedHelloResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RoutedHelloResponseDefaultTypeInternal _RoutedHelloResponse_default_instance_;

inline constexpr RoutedHelloRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        myname_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR RoutedHelloRequest::RoutedHelloRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(RoutedHelloRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct RoutedHelloRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RoutedHelloRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RoutedHelloRequestDefaultTypeInternal() {}
  union {
    RoutedHelloRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RoutedHelloRequestDefaultTypeInternal _RoutedHelloRequest_default_instance_;
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_RoutedHelloRpc_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_RoutedHelloRpc_2eproto = nullptr;
const ::uint32_t
    TableStruct_RoutedHelloRpc_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::RoutedHelloRequest, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::RoutedHelloRequest, _impl_.myname_),
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::RoutedHelloResponse, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::RoutedHelloResponse, _impl_.greeting_),
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::RoutedHelloRequest)},
        {5, sizeof(::RoutedHelloResponse)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::_RoutedHelloRequest_default_instance_._instance,
    &::_RoutedHelloResponse_default_instance_._instance,
};
const char descriptor_table_protodef_RoutedHelloRpc_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\024RoutedHelloRpc.proto\"$\n\022RoutedHelloReq"
    "uest\022\016\n\006myName\030\001 \001(\t\"\'\n\023RoutedHelloRespo"
    "nse\022\020\n\010greeting\030\001 \001(\t2N\n\025RoutedHelloRpcS"
    "ervice\0225\n\010sayHello\022\023.RoutedHelloRequest\032"
    "\024.RoutedHelloResponseB\002H\002b\006proto3"
};
static ::absl::once_flag descriptor_table_RoutedHelloRpc_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_RoutedHelloRpc_2eproto = {
    false,
    false,
    193,
    descriptor_table_protodef_RoutedHelloRpc_2eproto,
    "RoutedHelloRpc.proto",
    &descriptor_table_RoutedHelloRpc_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_RoutedHelloRpc_2eproto::offsets,
    file_level_enum_descriptors_RoutedHelloRpc_2eproto,
    file_level_service_descriptors_RoutedHelloRpc_2eproto,
};
// ===================================================================

class RoutedHelloRequest::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<RoutedHelloRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(RoutedHelloRequest, _impl_._has_bits_);
};

RoutedHelloRequest::RoutedHelloRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RoutedHelloRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:RoutedHelloRequest)
}
PROTOBUF_NDEBUG_INLINE RoutedHelloRequest::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::RoutedHelloRequest& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        myname_(arena, from.myname_) {}

RoutedHelloRequest::RoutedHelloRequest(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const RoutedHelloRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RoutedHelloRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  RoutedHelloRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:RoutedHelloRequest)
}
PROTOBUF_NDEBUG_INLINE RoutedHelloRequest::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        myname_(arena) {}

inline void RoutedHelloRequest::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
RoutedHelloRequest::~RoutedHelloRequest() {
  // @@protoc_insertion_point(destructor:RoutedHelloRequest)
  SharedDtor(*this);
}
inline void RoutedHelloRequest::SharedDtor(MessageLite& self) {
  RoutedHelloRequest& this_ = static_cast<RoutedHelloRequest&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.myname_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL RoutedHelloRequest::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) RoutedHelloRequest(arena);
}
constexpr auto RoutedHelloRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(RoutedHelloRequest),
                                            alignof(RoutedHelloRequest));
}
constexpr auto RoutedHelloRequest::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_RoutedHelloRequest_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &RoutedHelloRequest::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<RoutedHelloRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &RoutedHelloRequest::SharedDtor,
          static_cast<void (::google::protobuf::MessageLite::*)()>(&RoutedHelloRequest::ClearImpl),
              ::google::protobuf::Message::ByteSizeLongImpl, ::google::protobuf::Message::_InternalSerializeImpl
              ,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(RoutedHelloRequest, _impl_._cached_size_),
          false,
      },
      &RoutedHelloRequest::kDescriptorMethods,
      &descriptor_table_RoutedHelloRpc_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull RoutedHelloRequest_class_data_ =
        RoutedHelloRequest::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
RoutedHelloRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&RoutedHelloRequest_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(RoutedHelloRequest_class_data_.tc_table);
  return RoutedHelloRequest_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 33, 2>
RoutedHelloRequest::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(RoutedHelloRequest, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    RoutedHelloRequest_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::RoutedHelloRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string myName = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(RoutedHelloRequest, _impl_.myname_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string myName = 1;
    {PROTOBUF_FIELD_OFFSET(RoutedHelloRequest, _impl_.myname_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\22\6\0\0\0\0\0\0"
    "RoutedHelloRequest"
    "myName"
  }},
};
void RoutedHelloRequest::InternalSwap(RoutedHelloRequest* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata RoutedHelloRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class RoutedHelloResponse::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<RoutedHelloResponse>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(RoutedHelloResponse, _impl_._has_bits_);
};

RoutedHelloResponse::RoutedHelloResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RoutedHelloResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:RoutedHelloResponse)
}
PROTOBUF_NDEBUG_INLINE RoutedHelloResponse::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::RoutedHelloResponse& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        greeting_(arena, from.greeting_) {}

RoutedHelloResponse::RoutedHelloResponse(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const RoutedHelloResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RoutedHelloResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  RoutedHelloResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:RoutedHelloResponse)
}
PROTOBUF_NDEBUG_INLINE RoutedHelloResponse::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        greeting_(arena) {}

inline void RoutedHelloResponse::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
RoutedHelloResponse::~RoutedHelloResponse() {
  // @@protoc_insertion_point(destructor:RoutedHelloResponse)
  SharedDtor(*this);
}
inline void RoutedHelloResponse::SharedDtor(MessageLite& self) {
  RoutedHelloResponse& this_ = static_cast<RoutedHelloResponse&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.greeting_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL RoutedHelloResponse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) RoutedHelloResponse(arena);
}
constexpr auto RoutedHelloResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(RoutedHelloResponse),
                                            alignof(RoutedHelloResponse));
}
constexpr auto RoutedHelloResponse::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_RoutedHelloResponse_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &RoutedHelloResponse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<RoutedHelloResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &RoutedHelloResponse::SharedDtor,
          static_cast<void (::google::protobuf::MessageLite::*)()>(&RoutedHelloResponse::ClearImpl),
              ::google::protobuf::Message::ByteSizeLongImpl, ::google::protobuf::Message::_InternalSerializeImpl
              ,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(RoutedHelloResponse, _impl_._cached_size_),
          false,
      },
      &RoutedHelloResponse::kDescriptorMethods,
      &descriptor_table_RoutedHelloRpc_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull RoutedHelloResponse_class_data_ =
        RoutedHelloResponse::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
RoutedHelloResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&RoutedHelloResponse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(RoutedHelloResponse_class_data_.tc_table);
  return RoutedHelloResponse_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 36, 2>
RoutedHelloResponse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(RoutedHelloResponse, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    RoutedHelloResponse_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::RoutedHelloResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string greeting = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(RoutedHelloResponse, _impl_.greeting_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string greeting = 1;
    {PROTOBUF_FIELD_OFFSET(RoutedHelloResponse, _impl_.greeting_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\23\10\0\0\0\0\0\0"
    "RoutedHelloResponse"
    "greeting"
  }},
};
void RoutedHelloResponse::InternalSwap(RoutedHelloResponse* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata RoutedHelloResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_RoutedHelloRpc_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
