
#own stuff below
set(CMAKE_POLICY_DEFAULT_CMP0077 NEW)
set(VCPKG_TARGET_ARCHITECTURE arm64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_CMAKE_SYSTEM_NAME iOS)

set(CMAKE_CXX_STANDARD 26)
set(HOMEBREW_PREFIX $ENV{HOMEBREW_PREFIX})

# Homebrew llvm is keg-only; install-prerequisities.sh exports LLVM_PREFIX.
if(DEFINED ENV{LLVM_PREFIX})
    set(LLVM_PREFIX "$ENV{LLVM_PREFIX}")
else()
    set(LLVM_PREFIX "${HOMEBREW_PREFIX}/opt/llvm")
endif()
set(CMAKE_C_COMPILER "${LLVM_PREFIX}/bin/clang")
set(CMAKE_CXX_COMPILER "${LLVM_PREFIX}/bin/clang++")
set(ENV{CC} "${CMAKE_C_COMPILER}")
set(ENV{CXX} "${CMAKE_CXX_COMPILER}")

set(VCPKG_CMAKE_CONFIGURE_OPTIONS -DCMAKE_C_COMPILER=${LLVM_PREFIX}/bin/clang -DCMAKE_CXX_COMPILER=${LLVM_PREFIX}/bin/clang++ -DCMAKE_CXX_STANDARD=26 -DFOLLY_HAVE_CLOCK_GETTIME=1 -DFOLLY_MOBILE=0 -DIS_AARCH64_ARCH=0 -D__APPLE__=1 -DFOLLY_HAVE_MALLOC_USABLE_SIZE=0 -DPLATFORM=OS64)

set(VCPKG_CXX_FLAGS "-isystem ${LLVM_PREFIX}/include/c++/v1 -DFOLLY_MOBILE=0 -D_LIBCPP_AVAILABILITY_HAS_INIT_PRIMARY_EXCEPTION=0")
set(VCPKG_C_FLAGS "-isystem ${LLVM_PREFIX}/include/c++/v1 -DFOLLY_MOBILE=0 -D_LIBCPP_AVAILABILITY_HAS_INIT_PRIMARY_EXCEPTION=0")
set(VCPKG_LINKER_FLAGS "-lc++abi")

if(${PORT} MATCHES "usrsctp")
    set(VCPKG_CXX_FLAGS "${VCPKG_CXX_FLAGS} -D__APPLE_USE_RFC_2292")
    set(VCPKG_C_FLAGS "${VCPKG_C_FLAGS} -D__APPLE_USE_RFC_2292")
endif()

if(${PORT} MATCHES "folly")
    # folly's configure uses try_run() checks, which cannot execute when
    # cross-compiling; preset their results (same approach as
    # arm64-android.cmake). The values mirror what the checks detect when
    # they actually run on an arm64 Apple host (arm64-osx build).
    set(VCPKG_CMAKE_CONFIGURE_OPTIONS ${VCPKG_CMAKE_CONFIGURE_OPTIONS}
        -DHAVE_VSNPRINTF_ERRORS_EXITCODE=1
        -DHAVE_VSNPRINTF_ERRORS_EXITCODE__TRYRUN_OUTPUT=a
        -DFOLLY_HAVE_WCHAR_SUPPORT_EXITCODE=0
        -DFOLLY_HAVE_WCHAR_SUPPORT_EXITCODE__TRYRUN_OUTPUT=a
        -DFOLLY_HAVE_LINUX_VDSO_EXITCODE=1
        -DFOLLY_HAVE_LINUX_VDSO_EXITCODE__TRYRUN_OUTPUT=a
        -DFOLLY_HAVE_UNALIGNED_ACCESS_EXITCODE=0
        -DFOLLY_HAVE_UNALIGNED_ACCESS_EXITCODE__TRYRUN_OUTPUT=a
        -DFOLLY_HAVE_WEAK_SYMBOLS_EXITCODE=1
        -DFOLLY_HAVE_WEAK_SYMBOLS_EXITCODE__TRYRUN_OUTPUT=a)
endif()

set(ENV{VCPKG_CXX_FLAGS} "${VCPKG_CXX_FLAGS}")
set(ENV{VCPKG_C_FLAGS} "${VCPKG_C_FLAGS}")

#set(ENV{PLATFORM} "SIMULATORARM64")
set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE "${CMAKE_CURRENT_LIST_DIR}/../toolchains/ios.toolchain.cmake")
