set(VCPKG_TARGET_ARCHITECTURE arm64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_CMAKE_SYSTEM_NAME Darwin)
set(VCPKG_OSX_ARCHITECTURES arm64)

set(CMAKE_CXX_STANDARD 26)
set(HOMEBREW_PREFIX $ENV{HOMEBREW_PREFIX})

# Homebrew llvm is keg-only; install-prerequisities.sh exports LLVM_PREFIX.
if(DEFINED ENV{LLVM_PREFIX})
    set(LLVM_PREFIX "$ENV{LLVM_PREFIX}")
else()
    set(LLVM_PREFIX "${HOMEBREW_PREFIX}/opt/llvm")
endif()
set(CMAKE_C_COMPILER "${LLVM_PREFIX}/bin/clang")
set(CMAKE_CXX_COMPILER "${LLVM_PREFIX}/bin/clang++")
set(ENV{CC} "${CMAKE_C_COMPILER}")
set(ENV{CXX} "${CMAKE_CXX_COMPILER}")

set(VCPKG_CMAKE_CONFIGURE_OPTIONS
    -DCMAKE_C_COMPILER=${LLVM_PREFIX}/bin/clang
    -DCMAKE_CXX_COMPILER=${LLVM_PREFIX}/bin/clang++
    -DCMAKE_CXX_STANDARD=26 -DCMAKE_POLICY_VERSION_MINIMUM=3.5
    )

set(VCPKG_CXX_FLAGS "-isystem ${LLVM_PREFIX}/include/c++/v1")
set(VCPKG_C_FLAGS "-isystem ${LLVM_PREFIX}/include/c++/v1")
set(VCPKG_LINKER_FLAGS "-L${LLVM_PREFIX}/lib/c++ -Wl,-rpath,${LLVM_PREFIX}/lib/c++")

message(STATUS "OVERLAY TRIPLET arm64-osx loaded")
