// generated by the protocol buffer streamr pluging. DO NOT EDIT!
// generated from protobuf file "HelloRpc.proto"

#ifndef STREAMR_PROTORPC_HELLORPC_CLIENT_HPP
#define STREAMR_PROTORPC_HELLORPC_CLIENT_HPP

namespace streamr::protorpc {
  class HelloRpcService {
    public:
    
       virtual folly::task<HelloResponse> sayHello(const HelloRequest& request) = 0;
  }; // class HelloRpcService
}; //namespace 

#endif //STREAMR_PROTORPC_HELLORPC_CLIENT_HPP
