// generated by the protocol buffer streamr pluging. DO NOT EDIT!
// generated from protobuf file "HelloRpc.proto"

module;

// std::coroutine_traits must be visible in every translation unit
// that defines OR instantiates a coroutine; it cannot arrive through
// an imported BMI.
#include <coroutine> // IWYU pragma: keep

#include <chrono>
#include <optional>
#include "HelloRpc.pb.h" // NOLINT


export module streamr.protorpc.test.HelloRpcClient;

import streamr.utils.CoroutineHelper;

import streamr.protorpc.RpcCommunicator;

using streamr::protorpc::RpcCommunicator;

export namespace streamr::protorpc {
template <typename CallContextType>
class HelloRpcServiceClient {
private:
RpcCommunicator<CallContextType>& communicator;
public:
    explicit HelloRpcServiceClient(RpcCommunicator<CallContextType>& communicator) : communicator(communicator) {}
    folly::coro::Task<HelloResponse> sayHello(HelloRequest&& request, CallContextType&& callContext, std::optional<std::chrono::milliseconds> timeout = std::nullopt) {
        return communicator.template request<HelloResponse, HelloRequest>("sayHello", std::move(request), std::move(callContext), timeout);
    }
}; // class HelloRpcServiceClient
}; // namespace streamr::protorpc

