// generated by the protocol buffer streamr pluging. DO NOT EDIT!
// generated from protobuf file "TestProtos.proto"

#ifndef STREAMR_PROTORPC_TESTPROTOS_CLIENT_HPP
#define STREAMR_PROTORPC_TESTPROTOS_CLIENT_HPP

namespace streamr::protorpc {
  class DhtRpcService {
    public:
    
       virtual folly::task<ClosestPeersResponse> getClosestPeers(const ClosestPeersRequest& request) = 0;
       virtual folly::task<PingResponse> ping(const PingRequest& request) = 0;
       virtual folly::task<RouteMessageAck> routeMessage(const RouteMessageWrapper& request) = 0;
  }; // class DhtRpcService
  class OptionalService {
    public:
    
       virtual folly::task<OptionalResponse> getOptional(const OptionalRequest& request) = 0;
  }; // class OptionalService
}; //namespace 

#endif //STREAMR_PROTORPC_TESTPROTOS_CLIENT_HPP
