// generated by the protocol buffer streamr pluging. DO NOT EDIT!
// generated from protobuf file "TestProtos.proto"

module;

// std::coroutine_traits must be visible in every translation unit
// that defines OR instantiates a coroutine; it cannot arrive through
// an imported BMI.
#include <coroutine> // IWYU pragma: keep

#include <chrono>
#include <optional>
#include "TestProtos.pb.h" // NOLINT


export module streamr.protorpc.test.TestProtosClient;

import streamr.utils.CoroutineHelper;

import streamr.protorpc.RpcCommunicator;

using streamr::protorpc::RpcCommunicator;

export namespace streamr::protorpc {
template <typename CallContextType>
class DhtRpcServiceClient {
private:
RpcCommunicator<CallContextType>& communicator;
public:
    explicit DhtRpcServiceClient(RpcCommunicator<CallContextType>& communicator) : communicator(communicator) {}
    folly::coro::Task<ClosestPeersResponse> getClosestPeers(ClosestPeersRequest&& request, CallContextType&& callContext, std::optional<std::chrono::milliseconds> timeout = std::nullopt) {
        return communicator.template request<ClosestPeersResponse, ClosestPeersRequest>("getClosestPeers", std::move(request), std::move(callContext), timeout);
    }
    folly::coro::Task<PingResponse> ping(PingRequest&& request, CallContextType&& callContext, std::optional<std::chrono::milliseconds> timeout = std::nullopt) {
        return communicator.template request<PingResponse, PingRequest>("ping", std::move(request), std::move(callContext), timeout);
    }
    folly::coro::Task<RouteMessageAck> routeMessage(RouteMessageWrapper&& request, CallContextType&& callContext, std::optional<std::chrono::milliseconds> timeout = std::nullopt) {
        return communicator.template request<RouteMessageAck, RouteMessageWrapper>("routeMessage", std::move(request), std::move(callContext), timeout);
    }
}; // class DhtRpcServiceClient
template <typename CallContextType>
class OptionalServiceClient {
private:
RpcCommunicator<CallContextType>& communicator;
public:
    explicit OptionalServiceClient(RpcCommunicator<CallContextType>& communicator) : communicator(communicator) {}
    folly::coro::Task<OptionalResponse> getOptional(OptionalRequest&& request, CallContextType&& callContext, std::optional<std::chrono::milliseconds> timeout = std::nullopt) {
        return communicator.template request<OptionalResponse, OptionalRequest>("getOptional", std::move(request), std::move(callContext), timeout);
    }
}; // class OptionalServiceClient
}; // namespace streamr::protorpc

