// Generated by the protocol buffer streamr pluging. DO NOT EDIT!
// Generated from protobuf file "TestProtos.proto"

module;

#include "TestProtos.pb.h" // NOLINT
#include <folly/experimental/coro/Task.h>

export module streamr.protorpc.test.TestProtosServer;

export namespace streamr::protorpc {
template <typename CallContextType>
class DhtRpcService {
public:
   virtual ~DhtRpcService() = default;
   virtual ClosestPeersResponse getClosestPeers(const ClosestPeersRequest& request, const CallContextType& callContext) = 0;
   virtual PingResponse ping(const PingRequest& request, const CallContextType& callContext) = 0;
   virtual RouteMessageAck routeMessage(const RouteMessageWrapper& request, const CallContextType& callContext) = 0;
}; // class DhtRpcService
template <typename CallContextType>
class OptionalService {
public:
   virtual ~OptionalService() = default;
   virtual OptionalResponse getOptional(const OptionalRequest& request, const CallContextType& callContext) = 0;
}; // class OptionalService
}; // namespace streamr::protorpc

