// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: WakeUpRpc.proto
// Protobuf C++ Version: 6.33.4

#include "WakeUpRpc.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr WakeUpRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        reason_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR WakeUpRequest::WakeUpRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(WakeUpRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct WakeUpRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR WakeUpRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~WakeUpRequestDefaultTypeInternal() {}
  union {
    WakeUpRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 WakeUpRequestDefaultTypeInternal _WakeUpRequest_default_instance_;
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_WakeUpRpc_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_WakeUpRpc_2eproto = nullptr;
const ::uint32_t
    TableStruct_WakeUpRpc_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::WakeUpRequest, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::WakeUpRequest, _impl_.reason_),
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::WakeUpRequest)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::_WakeUpRequest_default_instance_._instance,
};
const char descriptor_table_protodef_WakeUpRpc_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\017WakeUpRpc.proto\032\033google/protobuf/empty"
    ".proto\"\037\n\rWakeUpRequest\022\016\n\006reason\030\001 \001(\t2"
    "D\n\020WakeUpRpcService\0220\n\006wakeUp\022\016.WakeUpRe"
    "quest\032\026.google.protobuf.EmptyB\002H\002b\006proto"
    "3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_WakeUpRpc_2eproto_deps[1] = {
        &::descriptor_table_google_2fprotobuf_2fempty_2eproto,
};
static ::absl::once_flag descriptor_table_WakeUpRpc_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_WakeUpRpc_2eproto = {
    false,
    false,
    161,
    descriptor_table_protodef_WakeUpRpc_2eproto,
    "WakeUpRpc.proto",
    &descriptor_table_WakeUpRpc_2eproto_once,
    descriptor_table_WakeUpRpc_2eproto_deps,
    1,
    1,
    schemas,
    file_default_instances,
    TableStruct_WakeUpRpc_2eproto::offsets,
    file_level_enum_descriptors_WakeUpRpc_2eproto,
    file_level_service_descriptors_WakeUpRpc_2eproto,
};
// ===================================================================

class WakeUpRequest::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<WakeUpRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(WakeUpRequest, _impl_._has_bits_);
};

WakeUpRequest::WakeUpRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, WakeUpRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:WakeUpRequest)
}
PROTOBUF_NDEBUG_INLINE WakeUpRequest::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::WakeUpRequest& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        reason_(arena, from.reason_) {}

WakeUpRequest::WakeUpRequest(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const WakeUpRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, WakeUpRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  WakeUpRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:WakeUpRequest)
}
PROTOBUF_NDEBUG_INLINE WakeUpRequest::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        reason_(arena) {}

inline void WakeUpRequest::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
WakeUpRequest::~WakeUpRequest() {
  // @@protoc_insertion_point(destructor:WakeUpRequest)
  SharedDtor(*this);
}
inline void WakeUpRequest::SharedDtor(MessageLite& self) {
  WakeUpRequest& this_ = static_cast<WakeUpRequest&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.reason_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL WakeUpRequest::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) WakeUpRequest(arena);
}
constexpr auto WakeUpRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(WakeUpRequest),
                                            alignof(WakeUpRequest));
}
constexpr auto WakeUpRequest::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_WakeUpRequest_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &WakeUpRequest::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<WakeUpRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &WakeUpRequest::SharedDtor,
          static_cast<void (::google::protobuf::MessageLite::*)()>(&WakeUpRequest::ClearImpl),
              ::google::protobuf::Message::ByteSizeLongImpl, ::google::protobuf::Message::_InternalSerializeImpl
              ,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(WakeUpRequest, _impl_._cached_size_),
          false,
      },
      &WakeUpRequest::kDescriptorMethods,
      &descriptor_table_WakeUpRpc_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull WakeUpRequest_class_data_ =
        WakeUpRequest::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
WakeUpRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&WakeUpRequest_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(WakeUpRequest_class_data_.tc_table);
  return WakeUpRequest_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 28, 2>
WakeUpRequest::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(WakeUpRequest, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    WakeUpRequest_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::WakeUpRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string reason = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(WakeUpRequest, _impl_.reason_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string reason = 1;
    {PROTOBUF_FIELD_OFFSET(WakeUpRequest, _impl_.reason_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\15\6\0\0\0\0\0\0"
    "WakeUpRequest"
    "reason"
  }},
};
void WakeUpRequest::InternalSwap(WakeUpRequest* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata WakeUpRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_WakeUpRpc_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
