// Generated by the protocol buffer streamr pluging. DO NOT EDIT!
// Generated from protobuf file "WakeUpRpc.proto"

#ifndef STREAMR_PROTORPC_WAKEUPRPC_SERVER_PB_H
#define STREAMR_PROTORPC_WAKEUPRPC_SERVER_PB_H

#include "WakeUpRpc.pb.h" // NOLINT
#include <folly/experimental/coro/Task.h>

namespace streamr::protorpc {
template <typename CallContextType>
class WakeUpRpcService {
public:
   virtual ~WakeUpRpcService() = default;
   virtual void wakeUp(const WakeUpRequest& request, const CallContextType& callContext) = 0;
}; // class WakeUpRpcService
}; // namespace streamr::protorpc

#endif // STREAMR_PROTORPC_WAKEUPRPC_SERVER_PB_H

