// generated by the protocol buffer streamr pluging. DO NOT EDIT!
// generated from protobuf file "WakeUpRpc.proto"

module;

// std::coroutine_traits must be visible in every translation unit
// that defines OR instantiates a coroutine; it cannot arrive through
// an imported BMI.

#include "WakeUpRpc.pb.h" // NOLINT


export module streamr.protorpc.test.WakeUpRpcClient;

import std;

import streamr.utils.CoroutineHelper;

import streamr.protorpc.RpcCommunicator;

using streamr::protorpc::RpcCommunicator;

export namespace streamr::protorpc {
template <typename CallContextType>
class WakeUpRpcServiceClient {
private:
RpcCommunicator<CallContextType>& communicator;
public:
    explicit WakeUpRpcServiceClient(RpcCommunicator<CallContextType>& communicator) : communicator(communicator) {}
    folly::coro::Task<void> wakeUp(WakeUpRequest&& request, CallContextType&& callContext, std::optional<std::chrono::milliseconds> timeout = std::nullopt) {
        return communicator.template notify<WakeUpRequest>("wakeUp", std::move(request), std::move(callContext), timeout);
    }
}; // class WakeUpRpcServiceClient
}; // namespace streamr::protorpc

