// Generated by the protocol buffer streamr pluging. DO NOT EDIT!
// Generated from protobuf file "WakeUpRpc.proto"

module;

#include "WakeUpRpc.pb.h" // NOLINT
#include <folly/experimental/coro/Task.h>

export module streamr.protorpc.test.WakeUpRpcServer;

export namespace streamr::protorpc {
template <typename CallContextType>
class WakeUpRpcService {
public:
   virtual ~WakeUpRpcService() = default;
   virtual void wakeUp(const WakeUpRequest& request, const CallContextType& callContext) = 0;
}; // class WakeUpRpcService
}; // namespace streamr::protorpc

