// generated by the protocol buffer streamr pluging. DO NOT EDIT!
// generated from protobuf file "WakeUpRpc.proto"

#ifndef STREAMR_PROTORPC_WAKEUPRPC_CLIENT_HPP
#define STREAMR_PROTORPC_WAKEUPRPC_CLIENT_HPP

namespace streamr::protorpc {
  class WakeUpRpcService {
    public:
    
       virtual folly::task<Empty> wakeUp(const WakeUpRequest& request) = 0;
  }; // class WakeUpRpcService
}; //namespace 

#endif //STREAMR_PROTORPC_WAKEUPRPC_CLIENT_HPP
