// Generated by the protocol buffer streamr pluging. DO NOT EDIT!
// Generated from protobuf file "WakeUpRpc.proto"

module;
#include <new>

// std::coroutine_traits must be visible in every translation unit
// that defines OR instantiates a coroutine; it cannot arrive through
// an imported BMI.

#include "WakeUpRpc.pb.h" // NOLINT

export module streamr.protorpc.test.WakeUpRpcServer;

import std;

import streamr.utils.CoroutineHelper;

export namespace streamr::protorpc {
template <typename CallContextType>
class WakeUpRpcService {
public:
   virtual ~WakeUpRpcService() = default;
   virtual void wakeUp(const WakeUpRequest& request, const CallContextType& callContext) = 0;
}; // class WakeUpRpcService
}; // namespace streamr::protorpc

