#ifndef STREAMER_PROTORPC_PLUGIN_CODE_GENERATOR_HPP
#define STREAMER_PROTORPC_PLUGIN_CODE_GENERATOR_HPP

#include <algorithm>
#include <cctype>
#include <iostream>
#include <sstream>
#include <string>
#include <google/protobuf/compiler/code_generator.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/io/zero_copy_stream.h>
#include "StreamPrinter.hpp"

namespace streamr::protorpc {

class PluginCodeGenerator : public google::protobuf::compiler::CodeGenerator {
public:
    PluginCodeGenerator() = default;
    ~PluginCodeGenerator() override = default;

    bool Generate(
        const google::protobuf::FileDescriptor* file,
        const std::string& parameter,
        google::protobuf::compiler::GeneratorContext* generatorContext,
        std::string* error) const override {
        return GenerateHeader(file, parameter, generatorContext, error) &&
            GenerateSource(file, parameter, generatorContext, error);
    }

    uint64_t GetSupportedFeatures() const override { // NOLINT
        // Indicate that this code generator supports proto3 optional fields.
        // (Note: don't release your code generator with this flag set until you
        // have actually added and tested your proto3 support!)
        return FEATURE_PROTO3_OPTIONAL;
    }

private:
    [[nodiscard]] static std::string toUpperCase(const std::string& str) {
        std::string result = str;
        std::transform(result.begin(), result.end(), result.begin(), ::toupper);
        return result;
    }

    // The plugin emits C++ module units (Phase 2.6 consolidation), so it
    // must know which module family the generated units belong to. The
    // consuming package passes it through protoc's plugin parameter:
    //   --streamr_out=module_prefix=streamr.dht:<outdir>
    [[nodiscard]] static std::string getModulePrefix(
        const std::string& parameter, std::string* error) {
        const std::string key = "module_prefix=";
        size_t pos = parameter.find(key);
        if (pos == std::string::npos) {
            *error =
                "the streamr plugin now generates C++ module units and "
                "requires the module_prefix parameter, e.g. "
                "--streamr_out=module_prefix=streamr.dht:<outdir>";
            return "";
        }
        size_t start = pos + key.size();
        size_t end = parameter.find(',', start);
        return parameter.substr(
            start, end == std::string::npos ? std::string::npos : end - start);
    }

    [[nodiscard]] static std::string getFilenameWithoutExtension(
        const std::string& filepath) {
        // Find the last directory separator
        size_t lastSlash = filepath.find_last_of("/\\");
        std::string filename = filepath.substr(lastSlash + 1);

        // Find the last dot in the filename
        size_t lastDot = filename.find_last_of('.');
        if (lastDot == std::string::npos) {
            return filename; // No extension found
        }
        return filename.substr(0, lastDot);
    }

    // Include path for the generated message-types header: the full proto
    // path with the extension swapped, NOT just the basename. The module
    // units land under modules/gen/ (away from the .pb.h), so the include
    // must resolve through the package's proto include root (src/proto),
    // where protoc mirrors the proto file's directory structure.
    [[nodiscard]] static std::string getPathWithoutExtension(
        const std::string& filepath) {
        size_t lastDot = filepath.find_last_of('.');
        size_t lastSlash = filepath.find_last_of("/\\");
        if (lastDot == std::string::npos ||
            (lastSlash != std::string::npos && lastDot < lastSlash)) {
            return filepath; // No extension found
        }
        return filepath.substr(0, lastDot);
    }

    bool GenerateServerHeader( // NOLINT
        const google::protobuf::FileDescriptor* file,
        const std::string& parameter,
        google::protobuf::compiler::GeneratorContext* generatorContext,
        std::string* error) const {
        bool emptyIncluded = false;
        const std::string protoFilename(file->name());
        const std::string protoFilenameWe =
            getFilenameWithoutExtension(protoFilename);
        const std::string modulePrefix = getModulePrefix(parameter, error);
        if (modulePrefix.empty()) {
            return false;
        }
        const std::string headerFilename = protoFilenameWe + ".server.cppm";
        const std::string typesFilename =
            getPathWithoutExtension(protoFilename) + ".pb.h";
        const std::string moduleName =
            modulePrefix + "." + protoFilenameWe + "Server";

        std::stringstream headerSs;

        headerSs
            << "// Generated by the protocol buffer streamr pluging. DO NOT EDIT!\n";
        headerSs << "// Generated from protobuf file \"" << protoFilename
                 << "\"\n";
        headerSs << "\n";
        headerSs << "module;\n\n";
        headerSs << "// std::coroutine_traits must be visible in every "
                    "translation unit\n";
        headerSs << "// that defines OR instantiates a coroutine; it cannot "
                    "arrive through\n";
        headerSs << "// an imported BMI.\n";
        headerSs << "#include <coroutine> // IWYU pragma: keep\n\n";
        headerSs << "#include \"" << typesFilename << "\" // NOLINT\n";

        std::stringstream sourceSs;

        sourceSs << "export module " << moduleName << ";\n\n";
        sourceSs << "import streamr.utils.CoroutineHelper;\n\n";
        if (file->package().empty()) {
            sourceSs << "export namespace streamr::protorpc {\n";
        } else {
            sourceSs << "export namespace " << file->package() << " {\n";
        }
        // for each services
        int numServices = file->service_count();
        for (int i = 0; i < numServices; i++) {
            const google::protobuf::ServiceDescriptor* service =
                file->service(i);
            const std::string serviceFullname(service->full_name());
            const std::string serviceName(service->name());

            sourceSs << "template <typename CallContextType>\n";
            sourceSs << "class " << serviceName << " {\n";
            sourceSs << "public:\n";
            sourceSs << "   virtual ~" << serviceName << "() = default;\n";
            // sourceSs << "    \n";
            // for each methods
            int numMethods = service->method_count();
            for (int j = 0; j < numMethods; j++) {
                const google::protobuf::MethodDescriptor* method =
                    service->method(j);
                const std::string methodFullname(method->full_name());
                const std::string methodName(method->name());

                const google::protobuf::Descriptor* methodInput =
                    method->input_type();
                const std::string methodInputFullname(methodInput->full_name());
                std::string methodInputName(methodInput->name());

                const google::protobuf::Descriptor* methodOutput =
                    method->output_type();

                if (methodInput->name() == "Empty") {
                    if (!emptyIncluded) {
                        headerSs << "#include <google/protobuf/empty.pb.h>\n";
                        emptyIncluded = true;
                    }
                    methodInputName = "google::protobuf::Empty";
                }

                const std::string methodOutputFullname(
                    methodOutput->full_name());
                std::string methodOutputName(methodOutput->name());

                if (methodOutputName == "Empty") {
                    methodOutputName = "void";
                }

                sourceSs
                    << "   virtual " << methodOutputName + " " << methodName
                    << "(const " << methodInputName
                    << "& request, const CallContextType& callContext) = 0;\n";
            }
            sourceSs << "}; // class " << serviceName << "\n";
        }

        if (file->package().empty()) {
            sourceSs << "}; // namespace streamr::protorpc\n";
        } else {
            sourceSs << "}; // namespace " << file->package() << "\n";
        }

        // output to the module unit file
        google::protobuf::io::ZeroCopyOutputStream* stream =
            generatorContext->Open(headerFilename);
        StreamPrinter printer(
            stream); // StreamPrinter takes ownership of the Stream
        const std::string headerBuffer = headerSs.str() + "\n";
        const std::string sourceBuffer = sourceSs.str() + "\n";

        printer.print(
            reinterpret_cast<const unsigned char*>(headerBuffer.c_str()),
            std::ssize(headerBuffer));
        printer.print(
            reinterpret_cast<const unsigned char*>(sourceBuffer.c_str()),
            std::ssize(sourceBuffer));
        return true;
    }

    bool GenerateClientHeader( // NOLINT
        const google::protobuf::FileDescriptor* file,
        const std::string& parameter,
        google::protobuf::compiler::GeneratorContext* generatorContext,
        std::string* error) const {
        bool emptyIncluded = false;
        const std::string protoFilename(file->name());
        const std::string protoFilenameWe =
            getFilenameWithoutExtension(protoFilename);
        const std::string modulePrefix = getModulePrefix(parameter, error);
        if (modulePrefix.empty()) {
            return false;
        }
        const std::string headerFilename = protoFilenameWe + ".client.cppm";
        const std::string typesFilename =
            getPathWithoutExtension(protoFilename) + ".pb.h";
        const std::string moduleName =
            modulePrefix + "." + protoFilenameWe + "Client";

        std::stringstream headerSs;

        headerSs
            << "// generated by the protocol buffer streamr pluging. DO NOT EDIT!\n";
        headerSs << "// generated from protobuf file \"" << protoFilename
                 << "\"\n";
        headerSs << "\n";
        headerSs << "module;\n\n";

        headerSs << "// std::coroutine_traits must be visible in every "
                    "translation unit\n";
        headerSs << "// that defines OR instantiates a coroutine; it cannot "
                    "arrive through\n";
        headerSs << "// an imported BMI.\n";
        headerSs << "#include <coroutine> // IWYU pragma: keep\n\n";
        headerSs << "#include <chrono>\n";
        headerSs << "#include <optional>\n";
        headerSs << "#include \"" << typesFilename << "\" // NOLINT\n";

        headerSs << "\n";

        std::stringstream sourceSs;

        sourceSs << "export module " << moduleName << ";\n\n";
        sourceSs << "import streamr.utils.CoroutineHelper;\n\n";
        // RpcCommunicator is consumed as a module (the textual header no
        // longer exists after the Phase 2.6 consolidation); the shorthand
        // stays at file scope so it is not exported.
        sourceSs << "import streamr.protorpc.RpcCommunicator;\n\n";
        sourceSs << "using streamr::protorpc::RpcCommunicator;\n\n";
        if (file->package().empty()) {
            sourceSs << "export namespace streamr::protorpc {\n";
        } else {
            sourceSs << "export namespace " << file->package() << " {\n";
        }

        // for each services
        int numServices = file->service_count();
        for (int i = 0; i < numServices; i++) {
            const google::protobuf::ServiceDescriptor* service =
                file->service(i);
            const std::string serviceFullname(service->full_name());
            const std::string serviceName(service->name());
            sourceSs << "template <typename CallContextType>\n";
            sourceSs << "class " << serviceName << "Client" << " {\n";
            sourceSs << "private:\n";
            sourceSs << "RpcCommunicator<CallContextType>& communicator;\n";
            sourceSs << "public:\n";
            sourceSs
                << "    explicit " << serviceName
                << "Client(RpcCommunicator<CallContextType>& communicator) : communicator(communicator) {}\n";
            // sourceSs << "    \n";
            // for each methods
            int numMethods = service->method_count();
            for (int j = 0; j < numMethods; j++) {
                const google::protobuf::MethodDescriptor* method =
                    service->method(j);
                const std::string methodFullname(method->full_name());
                const std::string methodName(method->name());

                const google::protobuf::Descriptor* methodInput =
                    method->input_type();
                const std::string methodInputFullname(methodInput->full_name());
                std::string methodInputName(methodInput->name());

                const google::protobuf::Descriptor* methodOutput =
                    method->output_type();

                if (methodInput->name() == "Empty") {
                    if (!emptyIncluded) {
                        headerSs << "#include <google/protobuf/empty.pb.h>\n";
                        emptyIncluded = true;
                    }
                    methodInputName = "google::protobuf::Empty";
                }

                const std::string methodOutputFullname(
                    methodOutput->full_name());
                std::string methodOutputName(methodOutput->name());

                if (methodOutputName == "Empty") {
                    methodOutputName = "void";
                }

                sourceSs
                    << "    folly::coro::Task<" + methodOutputName + "> "
                    << methodName << "(" << methodInputName
                    << "&& request, CallContextType&& callContext, std::optional<std::chrono::milliseconds> timeout = std::nullopt) {\n";
                sourceSs << "        return communicator.";
                if (methodOutputName == "void") {
                    sourceSs << "template notify<" << methodInputName << ">";
                } else {
                    sourceSs << "template request<" << methodOutputName << ", "
                             << methodInputName << ">";
                }
                sourceSs
                    << "(\"" << methodName
                    << "\", std::move(request), std::move(callContext), timeout);\n";
                sourceSs << "    }\n";
            }
            sourceSs << "}; // class " << serviceName << "Client\n";
        }

        if (file->package().empty()) {
            sourceSs << "}; // namespace streamr::protorpc\n";
        } else {
            sourceSs << "}; // namespace " << file->package() << "\n";
        }

        // output to the module unit file
        google::protobuf::io::ZeroCopyOutputStream* stream =
            generatorContext->Open(headerFilename);
        StreamPrinter printer(
            stream); // StreamPrinter takes ownership of the Stream
        const std::string headerBuffer = headerSs.str() + "\n";
        const std::string sourceBuffer = sourceSs.str() + "\n";

        printer.print(
            reinterpret_cast<const unsigned char*>(headerBuffer.c_str()),
            std::ssize(headerBuffer));
        printer.print(
            reinterpret_cast<const unsigned char*>(sourceBuffer.c_str()),
            std::ssize(sourceBuffer));
        return true;
    }

    bool GenerateHeader( // NOLINT
        const google::protobuf::FileDescriptor* file,
        const std::string& parameter,
        google::protobuf::compiler::GeneratorContext* generatorContext,
        std::string* error) const {
        std::cerr << "GenerateHeader()" << "\n";
        return GenerateServerHeader(file, parameter, generatorContext, error) &&
            GenerateClientHeader(file, parameter, generatorContext, error);
    }

    bool GenerateSource( // NOLINT
        const google::protobuf::FileDescriptor* /* file */,
        const std::string& /* parameter */,
        google::protobuf::compiler::GeneratorContext* /* generatorContext */,
        std::string* /* error */) const {
        std::cerr << "GenerateSource()" << "\n";
        return true;
    }
};
}; // namespace streamr::protorpc
#endif // PROTOBUF_STREAMR_PLUGIN_PLUGIN_CODE_GENERATOR_HPP