name: "cached install for ios"
description: "install dependencies, build and cache result, or restore from cache if present"

runs:
  using: "composite"
  steps:
    - name: cache homedir
      id: cache-homedir
      uses: actions/cache@v4
      with:
        key: cache-homedir-${{ hashFiles('./vcpkg.json') }}
        path: |
          ~/.cache
    - name: cache vcpkg installed
      id: cache-vcpkg-installed
      uses: actions/cache@v4
      with:
        key: cache-vcpkg-installed-${{ hashFiles('./vcpkg.json') }}
        path: |
          **/vcpkg_installed
    - name: install-prerequisities
      run:
        source install-prerequisities.sh
      shell: bash
    - name: install
      run:
        ./install.sh --ios --xcframework
      shell: bash
