// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: packages/proto-rpc/protos/ProtoRpc.proto
// Protobuf C++ Version: 6.33.4

#ifndef packages_2fproto_2drpc_2fprotos_2fProtoRpc_2eproto_2epb_2eh
#define packages_2fproto_2drpc_2fprotos_2fProtoRpc_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/map.h"  // IWYU pragma: export
#include "google/protobuf/map_type_handler.h"  // IWYU pragma: export
#include "google/protobuf/map_entry.h"
#include "google/protobuf/map_field.h"
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
#include "google/protobuf/empty.pb.h"
#include "google/protobuf/any.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_packages_2fproto_2drpc_2fprotos_2fProtoRpc_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_packages_2fproto_2drpc_2fprotos_2fProtoRpc_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_packages_2fproto_2drpc_2fprotos_2fProtoRpc_2eproto;
}  // extern "C"
namespace protorpc {
enum RpcErrorType : int;
extern const uint32_t RpcErrorType_internal_data_[];
class Mnfo2uhnf92hvqi2nviouq2hv9puhq;
struct Mnfo2uhnf92hvqi2nviouq2hv9puhqDefaultTypeInternal;
extern Mnfo2uhnf92hvqi2nviouq2hv9puhqDefaultTypeInternal _Mnfo2uhnf92hvqi2nviouq2hv9puhq_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Mnfo2uhnf92hvqi2nviouq2hv9puhq_class_data_;
class RpcMessage;
struct RpcMessageDefaultTypeInternal;
extern RpcMessageDefaultTypeInternal _RpcMessage_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull RpcMessage_class_data_;
class RpcMessage_HeaderEntry_DoNotUse;
struct RpcMessage_HeaderEntry_DoNotUseDefaultTypeInternal;
extern RpcMessage_HeaderEntry_DoNotUseDefaultTypeInternal _RpcMessage_HeaderEntry_DoNotUse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull RpcMessage_HeaderEntry_DoNotUse_class_data_;
}  // namespace protorpc
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::protorpc::RpcErrorType_internal_data_>
    internal::EnumTraitsImpl::value<::protorpc::RpcErrorType>;
}  // namespace protobuf
}  // namespace google

namespace protorpc {
enum RpcErrorType : int {
  SERVER_TIMEOUT = 0,
  CLIENT_TIMEOUT = 1,
  UNKNOWN_RPC_METHOD = 2,
  CLIENT_ERROR = 3,
  SERVER_ERROR = 4,
  RpcErrorType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  RpcErrorType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t RpcErrorType_internal_data_[];
inline constexpr RpcErrorType RpcErrorType_MIN =
    static_cast<RpcErrorType>(0);
inline constexpr RpcErrorType RpcErrorType_MAX =
    static_cast<RpcErrorType>(4);
inline bool RpcErrorType_IsValid(int value) {
  return 0 <= value && value <= 4;
}
inline constexpr int RpcErrorType_ARRAYSIZE = 4 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL RpcErrorType_descriptor();
template <typename T>
const ::std::string& RpcErrorType_Name(T value) {
  static_assert(::std::is_same<T, RpcErrorType>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to RpcErrorType_Name().");
  return RpcErrorType_Name(static_cast<RpcErrorType>(value));
}
template <>
inline const ::std::string& RpcErrorType_Name(RpcErrorType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<RpcErrorType_descriptor, 0, 4>(
      static_cast<int>(value));
}
inline bool RpcErrorType_Parse(
    ::absl::string_view name, RpcErrorType* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<RpcErrorType>(RpcErrorType_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class RpcMessage_HeaderEntry_DoNotUse final
    : public ::google::protobuf::internal::MapEntry<::std::string, ::std::string,
                             ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
                             ::google::protobuf::internal::WireFormatLite::TYPE_STRING> {
 public:
  using SuperType =
      ::google::protobuf::internal::MapEntry<::std::string, ::std::string,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING>;
  RpcMessage_HeaderEntry_DoNotUse();
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR RpcMessage_HeaderEntry_DoNotUse(::google::protobuf::internal::ConstantInitialized);
  explicit RpcMessage_HeaderEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr const void* PROTOBUF_NONNULL internal_default_instance() {
    return &_RpcMessage_HeaderEntry_DoNotUse_default_instance_;
  }


  static constexpr auto InternalGenerateClassData_();

 private:
  friend class ::google::protobuf::MessageLite;
  friend struct ::TableStruct_packages_2fproto_2drpc_2fprotos_2fProtoRpc_2eproto;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 48,
                                   2>
      _table_;

  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();
};
extern const ::google::protobuf::internal::ClassDataFull RpcMessage_HeaderEntry_DoNotUse_class_data_;
// -------------------------------------------------------------------

class RpcMessage final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:protorpc.RpcMessage) */ {
 public:
  inline RpcMessage() : RpcMessage(nullptr) {}
  ~RpcMessage() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(RpcMessage* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(RpcMessage));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR RpcMessage(::google::protobuf::internal::ConstantInitialized);

  inline RpcMessage(const RpcMessage& from) : RpcMessage(nullptr, from) {}
  inline RpcMessage(RpcMessage&& from) noexcept
      : RpcMessage(nullptr, ::std::move(from)) {}
  inline RpcMessage& operator=(const RpcMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline RpcMessage& operator=(RpcMessage&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RpcMessage& default_instance() {
    return *reinterpret_cast<const RpcMessage*>(
        &_RpcMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(RpcMessage& a, RpcMessage& b) { a.Swap(&b); }
  inline void Swap(RpcMessage* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RpcMessage* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RpcMessage* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<RpcMessage>(arena);
  }
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(RpcMessage* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "protorpc.RpcMessage"; }

  explicit RpcMessage(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  RpcMessage(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const RpcMessage& from);
  RpcMessage(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, RpcMessage&& from) noexcept
      : RpcMessage(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kRequestIdFieldNumber = 3,
    kErrorClassNameFieldNumber = 5,
    kErrorCodeFieldNumber = 6,
    kErrorMessageFieldNumber = 7,
    kBodyFieldNumber = 2,
    kErrorTypeFieldNumber = 4,
    kHeaderFieldNumber = 1,
  };
  // string requestId = 3;
  void clear_requestid() ;
  const ::std::string& requestid() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_requestid(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_requestid();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_requestid();
  void set_allocated_requestid(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_requestid() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_requestid(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_requestid();

  public:
  // optional string errorClassName = 5;
  bool has_errorclassname() const;
  void clear_errorclassname() ;
  const ::std::string& errorclassname() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_errorclassname(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_errorclassname();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_errorclassname();
  void set_allocated_errorclassname(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_errorclassname() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_errorclassname(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_errorclassname();

  public:
  // optional string errorCode = 6;
  bool has_errorcode() const;
  void clear_errorcode() ;
  const ::std::string& errorcode() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_errorcode(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_errorcode();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_errorcode();
  void set_allocated_errorcode(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_errorcode() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_errorcode(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_errorcode();

  public:
  // optional string errorMessage = 7;
  bool has_errormessage() const;
  void clear_errormessage() ;
  const ::std::string& errormessage() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_errormessage(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_errormessage();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_errormessage();
  void set_allocated_errormessage(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_errormessage() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_errormessage(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_errormessage();

  public:
  // .google.protobuf.Any body = 2;
  bool has_body() const;
  void clear_body() ;
  const ::google::protobuf::Any& body() const;
  [[nodiscard]] ::google::protobuf::Any* PROTOBUF_NULLABLE release_body();
  ::google::protobuf::Any* PROTOBUF_NONNULL mutable_body();
  void set_allocated_body(::google::protobuf::Any* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_body(::google::protobuf::Any* PROTOBUF_NULLABLE value);
  ::google::protobuf::Any* PROTOBUF_NULLABLE unsafe_arena_release_body();

  private:
  const ::google::protobuf::Any& _internal_body() const;
  ::google::protobuf::Any* PROTOBUF_NONNULL _internal_mutable_body();

  public:
  // optional .protorpc.RpcErrorType errorType = 4;
  bool has_errortype() const;
  void clear_errortype() ;
  ::protorpc::RpcErrorType errortype() const;
  void set_errortype(::protorpc::RpcErrorType value);

  private:
  ::protorpc::RpcErrorType _internal_errortype() const;
  void _internal_set_errortype(::protorpc::RpcErrorType value);

  public:
  // map<string, string> header = 1;
  int header_size() const;
  private:
  int _internal_header_size() const;

  public:
  void clear_header() ;
  const ::google::protobuf::Map<::std::string, ::std::string>& header() const;
  ::google::protobuf::Map<::std::string, ::std::string>* PROTOBUF_NONNULL mutable_header();

  private:
  const ::google::protobuf::Map<::std::string, ::std::string>& _internal_header() const;
  ::google::protobuf::Map<::std::string, ::std::string>* PROTOBUF_NONNULL _internal_mutable_header();

  public:
  // @@protoc_insertion_point(class_scope:protorpc.RpcMessage)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 7,
                                   2, 78,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const RpcMessage& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr requestid_;
    ::google::protobuf::internal::ArenaStringPtr errorclassname_;
    ::google::protobuf::internal::ArenaStringPtr errorcode_;
    ::google::protobuf::internal::ArenaStringPtr errormessage_;
    ::google::protobuf::Any* PROTOBUF_NULLABLE body_;
    int errortype_;
    ::google::protobuf::internal::MapField<RpcMessage_HeaderEntry_DoNotUse, ::std::string, ::std::string,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING>
        header_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_packages_2fproto_2drpc_2fprotos_2fProtoRpc_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull RpcMessage_class_data_;
// -------------------------------------------------------------------

class Mnfo2uhnf92hvqi2nviouq2hv9puhq final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:protorpc.Mnfo2uhnf92hvqi2nviouq2hv9puhq) */ {
 public:
  inline Mnfo2uhnf92hvqi2nviouq2hv9puhq() : Mnfo2uhnf92hvqi2nviouq2hv9puhq(nullptr) {}
  ~Mnfo2uhnf92hvqi2nviouq2hv9puhq() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Mnfo2uhnf92hvqi2nviouq2hv9puhq* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Mnfo2uhnf92hvqi2nviouq2hv9puhq));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Mnfo2uhnf92hvqi2nviouq2hv9puhq(::google::protobuf::internal::ConstantInitialized);

  inline Mnfo2uhnf92hvqi2nviouq2hv9puhq(const Mnfo2uhnf92hvqi2nviouq2hv9puhq& from) : Mnfo2uhnf92hvqi2nviouq2hv9puhq(nullptr, from) {}
  inline Mnfo2uhnf92hvqi2nviouq2hv9puhq(Mnfo2uhnf92hvqi2nviouq2hv9puhq&& from) noexcept
      : Mnfo2uhnf92hvqi2nviouq2hv9puhq(nullptr, ::std::move(from)) {}
  inline Mnfo2uhnf92hvqi2nviouq2hv9puhq& operator=(const Mnfo2uhnf92hvqi2nviouq2hv9puhq& from) {
    CopyFrom(from);
    return *this;
  }
  inline Mnfo2uhnf92hvqi2nviouq2hv9puhq& operator=(Mnfo2uhnf92hvqi2nviouq2hv9puhq&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Mnfo2uhnf92hvqi2nviouq2hv9puhq& default_instance() {
    return *reinterpret_cast<const Mnfo2uhnf92hvqi2nviouq2hv9puhq*>(
        &_Mnfo2uhnf92hvqi2nviouq2hv9puhq_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(Mnfo2uhnf92hvqi2nviouq2hv9puhq& a, Mnfo2uhnf92hvqi2nviouq2hv9puhq& b) { a.Swap(&b); }
  inline void Swap(Mnfo2uhnf92hvqi2nviouq2hv9puhq* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Mnfo2uhnf92hvqi2nviouq2hv9puhq* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Mnfo2uhnf92hvqi2nviouq2hv9puhq* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Mnfo2uhnf92hvqi2nviouq2hv9puhq>(arena);
  }
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Mnfo2uhnf92hvqi2nviouq2hv9puhq* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "protorpc.Mnfo2uhnf92hvqi2nviouq2hv9puhq"; }

  explicit Mnfo2uhnf92hvqi2nviouq2hv9puhq(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Mnfo2uhnf92hvqi2nviouq2hv9puhq(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Mnfo2uhnf92hvqi2nviouq2hv9puhq& from);
  Mnfo2uhnf92hvqi2nviouq2hv9puhq(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Mnfo2uhnf92hvqi2nviouq2hv9puhq&& from) noexcept
      : Mnfo2uhnf92hvqi2nviouq2hv9puhq(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kEmptyFieldNumber = 1,
  };
  // .google.protobuf.Empty empty = 1;
  bool has_empty() const;
  void clear_empty() ;
  const ::google::protobuf::Empty& empty() const;
  [[nodiscard]] ::google::protobuf::Empty* PROTOBUF_NULLABLE release_empty();
  ::google::protobuf::Empty* PROTOBUF_NONNULL mutable_empty();
  void set_allocated_empty(::google::protobuf::Empty* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_empty(::google::protobuf::Empty* PROTOBUF_NULLABLE value);
  ::google::protobuf::Empty* PROTOBUF_NULLABLE unsafe_arena_release_empty();

  private:
  const ::google::protobuf::Empty& _internal_empty() const;
  ::google::protobuf::Empty* PROTOBUF_NONNULL _internal_mutable_empty();

  public:
  // @@protoc_insertion_point(class_scope:protorpc.Mnfo2uhnf92hvqi2nviouq2hv9puhq)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Mnfo2uhnf92hvqi2nviouq2hv9puhq& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::Empty* PROTOBUF_NULLABLE empty_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_packages_2fproto_2drpc_2fprotos_2fProtoRpc_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Mnfo2uhnf92hvqi2nviouq2hv9puhq_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// RpcMessage

// map<string, string> header = 1;
inline int RpcMessage::_internal_header_size() const {
  return _internal_header().size();
}
inline int RpcMessage::header_size() const {
  return _internal_header_size();
}
inline void RpcMessage::clear_header() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.header_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000040U);
}
inline const ::google::protobuf::Map<::std::string, ::std::string>& RpcMessage::_internal_header() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.header_.GetMap();
}
inline const ::google::protobuf::Map<::std::string, ::std::string>& RpcMessage::header() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_map:protorpc.RpcMessage.header)
  return _internal_header();
}
inline ::google::protobuf::Map<::std::string, ::std::string>* PROTOBUF_NONNULL RpcMessage::_internal_mutable_header() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.header_.MutableMap();
}
inline ::google::protobuf::Map<::std::string, ::std::string>* PROTOBUF_NONNULL RpcMessage::mutable_header()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000040U);
  // @@protoc_insertion_point(field_mutable_map:protorpc.RpcMessage.header)
  return _internal_mutable_header();
}

// .google.protobuf.Any body = 2;
inline bool RpcMessage::has_body() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000010U);
  PROTOBUF_ASSUME(!value || _impl_.body_ != nullptr);
  return value;
}
inline const ::google::protobuf::Any& RpcMessage::_internal_body() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::google::protobuf::Any* p = _impl_.body_;
  return p != nullptr ? *p : reinterpret_cast<const ::google::protobuf::Any&>(::google::protobuf::_Any_default_instance_);
}
inline const ::google::protobuf::Any& RpcMessage::body() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:protorpc.RpcMessage.body)
  return _internal_body();
}
inline void RpcMessage::unsafe_arena_set_allocated_body(
    ::google::protobuf::Any* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.body_);
  }
  _impl_.body_ = reinterpret_cast<::google::protobuf::Any*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:protorpc.RpcMessage.body)
}
inline ::google::protobuf::Any* PROTOBUF_NULLABLE RpcMessage::release_body() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
  ::google::protobuf::Any* released = _impl_.body_;
  _impl_.body_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::google::protobuf::Any* PROTOBUF_NULLABLE RpcMessage::unsafe_arena_release_body() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:protorpc.RpcMessage.body)

  ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
  ::google::protobuf::Any* temp = _impl_.body_;
  _impl_.body_ = nullptr;
  return temp;
}
inline ::google::protobuf::Any* PROTOBUF_NONNULL RpcMessage::_internal_mutable_body() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.body_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::google::protobuf::Any>(GetArena());
    _impl_.body_ = reinterpret_cast<::google::protobuf::Any*>(p);
  }
  return _impl_.body_;
}
inline ::google::protobuf::Any* PROTOBUF_NONNULL RpcMessage::mutable_body()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  ::google::protobuf::Any* _msg = _internal_mutable_body();
  // @@protoc_insertion_point(field_mutable:protorpc.RpcMessage.body)
  return _msg;
}
inline void RpcMessage::set_allocated_body(::google::protobuf::Any* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.body_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
  }

  _impl_.body_ = reinterpret_cast<::google::protobuf::Any*>(value);
  // @@protoc_insertion_point(field_set_allocated:protorpc.RpcMessage.body)
}

// string requestId = 3;
inline void RpcMessage::clear_requestid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.requestid_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& RpcMessage::requestid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:protorpc.RpcMessage.requestId)
  return _internal_requestid();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void RpcMessage::set_requestid(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.requestid_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:protorpc.RpcMessage.requestId)
}
inline ::std::string* PROTOBUF_NONNULL RpcMessage::mutable_requestid()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_requestid();
  // @@protoc_insertion_point(field_mutable:protorpc.RpcMessage.requestId)
  return _s;
}
inline const ::std::string& RpcMessage::_internal_requestid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.requestid_.Get();
}
inline void RpcMessage::_internal_set_requestid(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.requestid_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL RpcMessage::_internal_mutable_requestid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.requestid_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE RpcMessage::release_requestid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:protorpc.RpcMessage.requestId)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.requestid_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.requestid_.Set("", GetArena());
  }
  return released;
}
inline void RpcMessage::set_allocated_requestid(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.requestid_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.requestid_.IsDefault()) {
    _impl_.requestid_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:protorpc.RpcMessage.requestId)
}

// optional .protorpc.RpcErrorType errorType = 4;
inline bool RpcMessage::has_errortype() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000020U);
  return value;
}
inline void RpcMessage::clear_errortype() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.errortype_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000020U);
}
inline ::protorpc::RpcErrorType RpcMessage::errortype() const {
  // @@protoc_insertion_point(field_get:protorpc.RpcMessage.errorType)
  return _internal_errortype();
}
inline void RpcMessage::set_errortype(::protorpc::RpcErrorType value) {
  _internal_set_errortype(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_set:protorpc.RpcMessage.errorType)
}
inline ::protorpc::RpcErrorType RpcMessage::_internal_errortype() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::protorpc::RpcErrorType>(_impl_.errortype_);
}
inline void RpcMessage::_internal_set_errortype(::protorpc::RpcErrorType value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.errortype_ = value;
}

// optional string errorClassName = 5;
inline bool RpcMessage::has_errorclassname() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  return value;
}
inline void RpcMessage::clear_errorclassname() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.errorclassname_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& RpcMessage::errorclassname() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:protorpc.RpcMessage.errorClassName)
  return _internal_errorclassname();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void RpcMessage::set_errorclassname(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.errorclassname_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:protorpc.RpcMessage.errorClassName)
}
inline ::std::string* PROTOBUF_NONNULL RpcMessage::mutable_errorclassname()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_errorclassname();
  // @@protoc_insertion_point(field_mutable:protorpc.RpcMessage.errorClassName)
  return _s;
}
inline const ::std::string& RpcMessage::_internal_errorclassname() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.errorclassname_.Get();
}
inline void RpcMessage::_internal_set_errorclassname(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.errorclassname_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL RpcMessage::_internal_mutable_errorclassname() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.errorclassname_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE RpcMessage::release_errorclassname() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:protorpc.RpcMessage.errorClassName)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.errorclassname_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.errorclassname_.Set("", GetArena());
  }
  return released;
}
inline void RpcMessage::set_allocated_errorclassname(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.errorclassname_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.errorclassname_.IsDefault()) {
    _impl_.errorclassname_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:protorpc.RpcMessage.errorClassName)
}

// optional string errorCode = 6;
inline bool RpcMessage::has_errorcode() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000004U);
  return value;
}
inline void RpcMessage::clear_errorcode() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.errorcode_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline const ::std::string& RpcMessage::errorcode() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:protorpc.RpcMessage.errorCode)
  return _internal_errorcode();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void RpcMessage::set_errorcode(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.errorcode_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:protorpc.RpcMessage.errorCode)
}
inline ::std::string* PROTOBUF_NONNULL RpcMessage::mutable_errorcode()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::std::string* _s = _internal_mutable_errorcode();
  // @@protoc_insertion_point(field_mutable:protorpc.RpcMessage.errorCode)
  return _s;
}
inline const ::std::string& RpcMessage::_internal_errorcode() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.errorcode_.Get();
}
inline void RpcMessage::_internal_set_errorcode(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.errorcode_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL RpcMessage::_internal_mutable_errorcode() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.errorcode_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE RpcMessage::release_errorcode() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:protorpc.RpcMessage.errorCode)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000004U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  auto* released = _impl_.errorcode_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.errorcode_.Set("", GetArena());
  }
  return released;
}
inline void RpcMessage::set_allocated_errorcode(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  _impl_.errorcode_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.errorcode_.IsDefault()) {
    _impl_.errorcode_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:protorpc.RpcMessage.errorCode)
}

// optional string errorMessage = 7;
inline bool RpcMessage::has_errormessage() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000008U);
  return value;
}
inline void RpcMessage::clear_errormessage() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.errormessage_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline const ::std::string& RpcMessage::errormessage() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:protorpc.RpcMessage.errorMessage)
  return _internal_errormessage();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void RpcMessage::set_errormessage(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  _impl_.errormessage_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:protorpc.RpcMessage.errorMessage)
}
inline ::std::string* PROTOBUF_NONNULL RpcMessage::mutable_errormessage()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::std::string* _s = _internal_mutable_errormessage();
  // @@protoc_insertion_point(field_mutable:protorpc.RpcMessage.errorMessage)
  return _s;
}
inline const ::std::string& RpcMessage::_internal_errormessage() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.errormessage_.Get();
}
inline void RpcMessage::_internal_set_errormessage(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.errormessage_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL RpcMessage::_internal_mutable_errormessage() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.errormessage_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE RpcMessage::release_errormessage() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:protorpc.RpcMessage.errorMessage)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000008U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  auto* released = _impl_.errormessage_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.errormessage_.Set("", GetArena());
  }
  return released;
}
inline void RpcMessage::set_allocated_errormessage(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  }
  _impl_.errormessage_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.errormessage_.IsDefault()) {
    _impl_.errormessage_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:protorpc.RpcMessage.errorMessage)
}

// -------------------------------------------------------------------

// Mnfo2uhnf92hvqi2nviouq2hv9puhq

// .google.protobuf.Empty empty = 1;
inline bool Mnfo2uhnf92hvqi2nviouq2hv9puhq::has_empty() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  PROTOBUF_ASSUME(!value || _impl_.empty_ != nullptr);
  return value;
}
inline const ::google::protobuf::Empty& Mnfo2uhnf92hvqi2nviouq2hv9puhq::_internal_empty() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::google::protobuf::Empty* p = _impl_.empty_;
  return p != nullptr ? *p : reinterpret_cast<const ::google::protobuf::Empty&>(::google::protobuf::_Empty_default_instance_);
}
inline const ::google::protobuf::Empty& Mnfo2uhnf92hvqi2nviouq2hv9puhq::empty() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:protorpc.Mnfo2uhnf92hvqi2nviouq2hv9puhq.empty)
  return _internal_empty();
}
inline void Mnfo2uhnf92hvqi2nviouq2hv9puhq::unsafe_arena_set_allocated_empty(
    ::google::protobuf::Empty* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.empty_);
  }
  _impl_.empty_ = reinterpret_cast<::google::protobuf::Empty*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:protorpc.Mnfo2uhnf92hvqi2nviouq2hv9puhq.empty)
}
inline ::google::protobuf::Empty* PROTOBUF_NULLABLE Mnfo2uhnf92hvqi2nviouq2hv9puhq::release_empty() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::google::protobuf::Empty* released = _impl_.empty_;
  _impl_.empty_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::google::protobuf::Empty* PROTOBUF_NULLABLE Mnfo2uhnf92hvqi2nviouq2hv9puhq::unsafe_arena_release_empty() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:protorpc.Mnfo2uhnf92hvqi2nviouq2hv9puhq.empty)

  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::google::protobuf::Empty* temp = _impl_.empty_;
  _impl_.empty_ = nullptr;
  return temp;
}
inline ::google::protobuf::Empty* PROTOBUF_NONNULL Mnfo2uhnf92hvqi2nviouq2hv9puhq::_internal_mutable_empty() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.empty_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::google::protobuf::Empty>(GetArena());
    _impl_.empty_ = reinterpret_cast<::google::protobuf::Empty*>(p);
  }
  return _impl_.empty_;
}
inline ::google::protobuf::Empty* PROTOBUF_NONNULL Mnfo2uhnf92hvqi2nviouq2hv9puhq::mutable_empty()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::google::protobuf::Empty* _msg = _internal_mutable_empty();
  // @@protoc_insertion_point(field_mutable:protorpc.Mnfo2uhnf92hvqi2nviouq2hv9puhq.empty)
  return _msg;
}
inline void Mnfo2uhnf92hvqi2nviouq2hv9puhq::set_allocated_empty(::google::protobuf::Empty* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.empty_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }

  _impl_.empty_ = reinterpret_cast<::google::protobuf::Empty*>(value);
  // @@protoc_insertion_point(field_set_allocated:protorpc.Mnfo2uhnf92hvqi2nviouq2hv9puhq.empty)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace protorpc


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::protorpc::RpcErrorType> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::protorpc::RpcErrorType>() {
  return ::protorpc::RpcErrorType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // packages_2fproto_2drpc_2fprotos_2fProtoRpc_2eproto_2epb_2eh
