[build-system]
requires = [ "hatchling",]
build-backend = "hatchling.build"

[project]
name = "libstreamrproxyclient"
version = "2.0.5"
dependencies = []
requires-python = ">=3.12"
description = "Python bindings for libstreamrproxyclient"
readme = "README.md"
keywords = [ "streamr", "proxy", "client",]
classifiers = [ "Development Status :: 4 - Beta", "Programming Language :: Python",]
[[project.authors]]
name = "Petri Savolainen"
email = "petri.savolainen@streamr.network"

[[project.maintainers]]
name = "Petri Savolainen"
email = "petri.savolainen@streamr.network"

[project.license]
file = "LICENSE.txt"

[project.urls]
Homepage = "https://github.com/streamr-dev/native-sdk"
Documentation = "https://github.com/streamr-dev/native-sdk/tree/main/wrappers/python"
Repository = "https://github.com/streamr-dev/native-sdk.git"

[tool.hatch.build.targets.wheel]
packages = [ "src/streamrproxyclient",]

[tool.hatch.build.targets.wheel.hooks.custom]
