// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: media.proto
// Protobuf Java Version: 4.27.1

package network.streamr.streamrvideo.data.model.proto;

/**
 * Protobuf type {@code network.streamr.streamrvideo.data.model.proto.Heartbeat}
 */
public  final class Heartbeat extends
    com.google.protobuf.GeneratedMessageLite<
        Heartbeat, Heartbeat.Builder> implements
    // @@protoc_insertion_point(message_implements:network.streamr.streamrvideo.data.model.proto.Heartbeat)
    HeartbeatOrBuilder {
  private Heartbeat() {
    nodeId_ = "";
  }
  public static final int NODEID_FIELD_NUMBER = 1;
  private java.lang.String nodeId_;
  /**
   * <code>string nodeId = 1;</code>
   * @return The nodeId.
   */
  @java.lang.Override
  public java.lang.String getNodeId() {
    return nodeId_;
  }
  /**
   * <code>string nodeId = 1;</code>
   * @return The bytes for nodeId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNodeIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(nodeId_);
  }
  /**
   * <code>string nodeId = 1;</code>
   * @param value The nodeId to set.
   */
  private void setNodeId(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    nodeId_ = value;
  }
  /**
   * <code>string nodeId = 1;</code>
   */
  private void clearNodeId() {

    nodeId_ = getDefaultInstance().getNodeId();
  }
  /**
   * <code>string nodeId = 1;</code>
   * @param value The bytes for nodeId to set.
   */
  private void setNodeIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    nodeId_ = value.toStringUtf8();

  }

  public static network.streamr.streamrvideo.data.model.proto.Heartbeat parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static network.streamr.streamrvideo.data.model.proto.Heartbeat parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static network.streamr.streamrvideo.data.model.proto.Heartbeat parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static network.streamr.streamrvideo.data.model.proto.Heartbeat parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static network.streamr.streamrvideo.data.model.proto.Heartbeat parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static network.streamr.streamrvideo.data.model.proto.Heartbeat parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static network.streamr.streamrvideo.data.model.proto.Heartbeat parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static network.streamr.streamrvideo.data.model.proto.Heartbeat parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static network.streamr.streamrvideo.data.model.proto.Heartbeat parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static network.streamr.streamrvideo.data.model.proto.Heartbeat parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static network.streamr.streamrvideo.data.model.proto.Heartbeat parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static network.streamr.streamrvideo.data.model.proto.Heartbeat parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(network.streamr.streamrvideo.data.model.proto.Heartbeat prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code network.streamr.streamrvideo.data.model.proto.Heartbeat}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        network.streamr.streamrvideo.data.model.proto.Heartbeat, Builder> implements
      // @@protoc_insertion_point(builder_implements:network.streamr.streamrvideo.data.model.proto.Heartbeat)
      network.streamr.streamrvideo.data.model.proto.HeartbeatOrBuilder {
    // Construct using network.streamr.streamrvideo.data.model.proto.Heartbeat.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string nodeId = 1;</code>
     * @return The nodeId.
     */
    @java.lang.Override
    public java.lang.String getNodeId() {
      return instance.getNodeId();
    }
    /**
     * <code>string nodeId = 1;</code>
     * @return The bytes for nodeId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNodeIdBytes() {
      return instance.getNodeIdBytes();
    }
    /**
     * <code>string nodeId = 1;</code>
     * @param value The nodeId to set.
     * @return This builder for chaining.
     */
    public Builder setNodeId(
        java.lang.String value) {
      copyOnWrite();
      instance.setNodeId(value);
      return this;
    }
    /**
     * <code>string nodeId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearNodeId() {
      copyOnWrite();
      instance.clearNodeId();
      return this;
    }
    /**
     * <code>string nodeId = 1;</code>
     * @param value The bytes for nodeId to set.
     * @return This builder for chaining.
     */
    public Builder setNodeIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setNodeIdBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:network.streamr.streamrvideo.data.model.proto.Heartbeat)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new network.streamr.streamrvideo.data.model.proto.Heartbeat();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "nodeId_",
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<network.streamr.streamrvideo.data.model.proto.Heartbeat> parser = PARSER;
        if (parser == null) {
          synchronized (network.streamr.streamrvideo.data.model.proto.Heartbeat.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<network.streamr.streamrvideo.data.model.proto.Heartbeat>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:network.streamr.streamrvideo.data.model.proto.Heartbeat)
  private static final network.streamr.streamrvideo.data.model.proto.Heartbeat DEFAULT_INSTANCE;
  static {
    Heartbeat defaultInstance = new Heartbeat();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      Heartbeat.class, defaultInstance);
  }

  public static network.streamr.streamrvideo.data.model.proto.Heartbeat getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Heartbeat> PARSER;

  public static com.google.protobuf.Parser<Heartbeat> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

