// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: media.proto
// Protobuf Java Version: 4.27.1

package network.streamr.streamrvideo.data.model.proto;

public interface MediaPacketFragmentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:network.streamr.streamrvideo.data.model.proto.MediaPacketFragment)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>int64 packetNumber = 1;</code>
   * @return The packetNumber.
   */
  long getPacketNumber();

  /**
   * <code>int32 fragmentNumber = 2;</code>
   * @return The fragmentNumber.
   */
  int getFragmentNumber();

  /**
   * <code>int32 numberOfFragments = 3;</code>
   * @return The numberOfFragments.
   */
  int getNumberOfFragments();

  /**
   * <code>bytes data = 4;</code>
   * @return The data.
   */
  com.google.protobuf.ByteString getData();
}
