// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: media.proto
// Protobuf Java Version: 4.27.1

package network.streamr.streamrvideo.data.model.proto;

/**
 * Protobuf type {@code network.streamr.streamrvideo.data.model.proto.Message}
 */
public  final class Message extends
    com.google.protobuf.GeneratedMessageLite<
        Message, Message.Builder> implements
    // @@protoc_insertion_point(message_implements:network.streamr.streamrvideo.data.model.proto.Message)
    MessageOrBuilder {
  private Message() {
    messageId_ = "";
  }
  private int bodyCase_ = 0;
  private java.lang.Object body_;
  public enum BodyCase {
    MEDIAPACKETFRAGMENT(2),
    HEARTBEAT(3),
    LEAVE(4),
    VIEWERINFO(5),
    BODY_NOT_SET(0);
    private final int value;
    private BodyCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static BodyCase valueOf(int value) {
      return forNumber(value);
    }

    public static BodyCase forNumber(int value) {
      switch (value) {
        case 2: return MEDIAPACKETFRAGMENT;
        case 3: return HEARTBEAT;
        case 4: return LEAVE;
        case 5: return VIEWERINFO;
        case 0: return BODY_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  @java.lang.Override
  public BodyCase
  getBodyCase() {
    return BodyCase.forNumber(
        bodyCase_);
  }

  private void clearBody() {
    bodyCase_ = 0;
    body_ = null;
  }

  public static final int MESSAGEID_FIELD_NUMBER = 1;
  private java.lang.String messageId_;
  /**
   * <code>string messageId = 1;</code>
   * @return The messageId.
   */
  @java.lang.Override
  public java.lang.String getMessageId() {
    return messageId_;
  }
  /**
   * <code>string messageId = 1;</code>
   * @return The bytes for messageId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMessageIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(messageId_);
  }
  /**
   * <code>string messageId = 1;</code>
   * @param value The messageId to set.
   */
  private void setMessageId(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    messageId_ = value;
  }
  /**
   * <code>string messageId = 1;</code>
   */
  private void clearMessageId() {

    messageId_ = getDefaultInstance().getMessageId();
  }
  /**
   * <code>string messageId = 1;</code>
   * @param value The bytes for messageId to set.
   */
  private void setMessageIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    messageId_ = value.toStringUtf8();

  }

  public static final int MEDIAPACKETFRAGMENT_FIELD_NUMBER = 2;
  /**
   * <code>.network.streamr.streamrvideo.data.model.proto.MediaPacketFragment mediaPacketFragment = 2;</code>
   */
  @java.lang.Override
  public boolean hasMediaPacketFragment() {
    return bodyCase_ == 2;
  }
  /**
   * <code>.network.streamr.streamrvideo.data.model.proto.MediaPacketFragment mediaPacketFragment = 2;</code>
   */
  @java.lang.Override
  public network.streamr.streamrvideo.data.model.proto.MediaPacketFragment getMediaPacketFragment() {
    if (bodyCase_ == 2) {
       return (network.streamr.streamrvideo.data.model.proto.MediaPacketFragment) body_;
    }
    return network.streamr.streamrvideo.data.model.proto.MediaPacketFragment.getDefaultInstance();
  }
  /**
   * <code>.network.streamr.streamrvideo.data.model.proto.MediaPacketFragment mediaPacketFragment = 2;</code>
   */
  private void setMediaPacketFragment(network.streamr.streamrvideo.data.model.proto.MediaPacketFragment value) {
    value.getClass();
  body_ = value;
    bodyCase_ = 2;
  }
  /**
   * <code>.network.streamr.streamrvideo.data.model.proto.MediaPacketFragment mediaPacketFragment = 2;</code>
   */
  private void mergeMediaPacketFragment(network.streamr.streamrvideo.data.model.proto.MediaPacketFragment value) {
    value.getClass();
  if (bodyCase_ == 2 &&
        body_ != network.streamr.streamrvideo.data.model.proto.MediaPacketFragment.getDefaultInstance()) {
      body_ = network.streamr.streamrvideo.data.model.proto.MediaPacketFragment.newBuilder((network.streamr.streamrvideo.data.model.proto.MediaPacketFragment) body_)
          .mergeFrom(value).buildPartial();
    } else {
      body_ = value;
    }
    bodyCase_ = 2;
  }
  /**
   * <code>.network.streamr.streamrvideo.data.model.proto.MediaPacketFragment mediaPacketFragment = 2;</code>
   */
  private void clearMediaPacketFragment() {
    if (bodyCase_ == 2) {
      bodyCase_ = 0;
      body_ = null;
    }
  }

  public static final int HEARTBEAT_FIELD_NUMBER = 3;
  /**
   * <code>.network.streamr.streamrvideo.data.model.proto.Heartbeat heartbeat = 3;</code>
   */
  @java.lang.Override
  public boolean hasHeartbeat() {
    return bodyCase_ == 3;
  }
  /**
   * <code>.network.streamr.streamrvideo.data.model.proto.Heartbeat heartbeat = 3;</code>
   */
  @java.lang.Override
  public network.streamr.streamrvideo.data.model.proto.Heartbeat getHeartbeat() {
    if (bodyCase_ == 3) {
       return (network.streamr.streamrvideo.data.model.proto.Heartbeat) body_;
    }
    return network.streamr.streamrvideo.data.model.proto.Heartbeat.getDefaultInstance();
  }
  /**
   * <code>.network.streamr.streamrvideo.data.model.proto.Heartbeat heartbeat = 3;</code>
   */
  private void setHeartbeat(network.streamr.streamrvideo.data.model.proto.Heartbeat value) {
    value.getClass();
  body_ = value;
    bodyCase_ = 3;
  }
  /**
   * <code>.network.streamr.streamrvideo.data.model.proto.Heartbeat heartbeat = 3;</code>
   */
  private void mergeHeartbeat(network.streamr.streamrvideo.data.model.proto.Heartbeat value) {
    value.getClass();
  if (bodyCase_ == 3 &&
        body_ != network.streamr.streamrvideo.data.model.proto.Heartbeat.getDefaultInstance()) {
      body_ = network.streamr.streamrvideo.data.model.proto.Heartbeat.newBuilder((network.streamr.streamrvideo.data.model.proto.Heartbeat) body_)
          .mergeFrom(value).buildPartial();
    } else {
      body_ = value;
    }
    bodyCase_ = 3;
  }
  /**
   * <code>.network.streamr.streamrvideo.data.model.proto.Heartbeat heartbeat = 3;</code>
   */
  private void clearHeartbeat() {
    if (bodyCase_ == 3) {
      bodyCase_ = 0;
      body_ = null;
    }
  }

  public static final int LEAVE_FIELD_NUMBER = 4;
  /**
   * <code>.network.streamr.streamrvideo.data.model.proto.Leave leave = 4;</code>
   */
  @java.lang.Override
  public boolean hasLeave() {
    return bodyCase_ == 4;
  }
  /**
   * <code>.network.streamr.streamrvideo.data.model.proto.Leave leave = 4;</code>
   */
  @java.lang.Override
  public network.streamr.streamrvideo.data.model.proto.Leave getLeave() {
    if (bodyCase_ == 4) {
       return (network.streamr.streamrvideo.data.model.proto.Leave) body_;
    }
    return network.streamr.streamrvideo.data.model.proto.Leave.getDefaultInstance();
  }
  /**
   * <code>.network.streamr.streamrvideo.data.model.proto.Leave leave = 4;</code>
   */
  private void setLeave(network.streamr.streamrvideo.data.model.proto.Leave value) {
    value.getClass();
  body_ = value;
    bodyCase_ = 4;
  }
  /**
   * <code>.network.streamr.streamrvideo.data.model.proto.Leave leave = 4;</code>
   */
  private void mergeLeave(network.streamr.streamrvideo.data.model.proto.Leave value) {
    value.getClass();
  if (bodyCase_ == 4 &&
        body_ != network.streamr.streamrvideo.data.model.proto.Leave.getDefaultInstance()) {
      body_ = network.streamr.streamrvideo.data.model.proto.Leave.newBuilder((network.streamr.streamrvideo.data.model.proto.Leave) body_)
          .mergeFrom(value).buildPartial();
    } else {
      body_ = value;
    }
    bodyCase_ = 4;
  }
  /**
   * <code>.network.streamr.streamrvideo.data.model.proto.Leave leave = 4;</code>
   */
  private void clearLeave() {
    if (bodyCase_ == 4) {
      bodyCase_ = 0;
      body_ = null;
    }
  }

  public static final int VIEWERINFO_FIELD_NUMBER = 5;
  /**
   * <code>.network.streamr.streamrvideo.data.model.proto.ViewerInfo ViewerInfo = 5;</code>
   */
  @java.lang.Override
  public boolean hasViewerInfo() {
    return bodyCase_ == 5;
  }
  /**
   * <code>.network.streamr.streamrvideo.data.model.proto.ViewerInfo ViewerInfo = 5;</code>
   */
  @java.lang.Override
  public network.streamr.streamrvideo.data.model.proto.ViewerInfo getViewerInfo() {
    if (bodyCase_ == 5) {
       return (network.streamr.streamrvideo.data.model.proto.ViewerInfo) body_;
    }
    return network.streamr.streamrvideo.data.model.proto.ViewerInfo.getDefaultInstance();
  }
  /**
   * <code>.network.streamr.streamrvideo.data.model.proto.ViewerInfo ViewerInfo = 5;</code>
   */
  private void setViewerInfo(network.streamr.streamrvideo.data.model.proto.ViewerInfo value) {
    value.getClass();
  body_ = value;
    bodyCase_ = 5;
  }
  /**
   * <code>.network.streamr.streamrvideo.data.model.proto.ViewerInfo ViewerInfo = 5;</code>
   */
  private void mergeViewerInfo(network.streamr.streamrvideo.data.model.proto.ViewerInfo value) {
    value.getClass();
  if (bodyCase_ == 5 &&
        body_ != network.streamr.streamrvideo.data.model.proto.ViewerInfo.getDefaultInstance()) {
      body_ = network.streamr.streamrvideo.data.model.proto.ViewerInfo.newBuilder((network.streamr.streamrvideo.data.model.proto.ViewerInfo) body_)
          .mergeFrom(value).buildPartial();
    } else {
      body_ = value;
    }
    bodyCase_ = 5;
  }
  /**
   * <code>.network.streamr.streamrvideo.data.model.proto.ViewerInfo ViewerInfo = 5;</code>
   */
  private void clearViewerInfo() {
    if (bodyCase_ == 5) {
      bodyCase_ = 0;
      body_ = null;
    }
  }

  public static network.streamr.streamrvideo.data.model.proto.Message parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static network.streamr.streamrvideo.data.model.proto.Message parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static network.streamr.streamrvideo.data.model.proto.Message parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static network.streamr.streamrvideo.data.model.proto.Message parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static network.streamr.streamrvideo.data.model.proto.Message parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static network.streamr.streamrvideo.data.model.proto.Message parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static network.streamr.streamrvideo.data.model.proto.Message parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static network.streamr.streamrvideo.data.model.proto.Message parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static network.streamr.streamrvideo.data.model.proto.Message parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static network.streamr.streamrvideo.data.model.proto.Message parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static network.streamr.streamrvideo.data.model.proto.Message parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static network.streamr.streamrvideo.data.model.proto.Message parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(network.streamr.streamrvideo.data.model.proto.Message prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code network.streamr.streamrvideo.data.model.proto.Message}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        network.streamr.streamrvideo.data.model.proto.Message, Builder> implements
      // @@protoc_insertion_point(builder_implements:network.streamr.streamrvideo.data.model.proto.Message)
      network.streamr.streamrvideo.data.model.proto.MessageOrBuilder {
    // Construct using network.streamr.streamrvideo.data.model.proto.Message.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }

    @java.lang.Override
    public BodyCase
        getBodyCase() {
      return instance.getBodyCase();
    }

    public Builder clearBody() {
      copyOnWrite();
      instance.clearBody();
      return this;
    }


    /**
     * <code>string messageId = 1;</code>
     * @return The messageId.
     */
    @java.lang.Override
    public java.lang.String getMessageId() {
      return instance.getMessageId();
    }
    /**
     * <code>string messageId = 1;</code>
     * @return The bytes for messageId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageIdBytes() {
      return instance.getMessageIdBytes();
    }
    /**
     * <code>string messageId = 1;</code>
     * @param value The messageId to set.
     * @return This builder for chaining.
     */
    public Builder setMessageId(
        java.lang.String value) {
      copyOnWrite();
      instance.setMessageId(value);
      return this;
    }
    /**
     * <code>string messageId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessageId() {
      copyOnWrite();
      instance.clearMessageId();
      return this;
    }
    /**
     * <code>string messageId = 1;</code>
     * @param value The bytes for messageId to set.
     * @return This builder for chaining.
     */
    public Builder setMessageIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setMessageIdBytes(value);
      return this;
    }

    /**
     * <code>.network.streamr.streamrvideo.data.model.proto.MediaPacketFragment mediaPacketFragment = 2;</code>
     */
    @java.lang.Override
    public boolean hasMediaPacketFragment() {
      return instance.hasMediaPacketFragment();
    }
    /**
     * <code>.network.streamr.streamrvideo.data.model.proto.MediaPacketFragment mediaPacketFragment = 2;</code>
     */
    @java.lang.Override
    public network.streamr.streamrvideo.data.model.proto.MediaPacketFragment getMediaPacketFragment() {
      return instance.getMediaPacketFragment();
    }
    /**
     * <code>.network.streamr.streamrvideo.data.model.proto.MediaPacketFragment mediaPacketFragment = 2;</code>
     */
    public Builder setMediaPacketFragment(network.streamr.streamrvideo.data.model.proto.MediaPacketFragment value) {
      copyOnWrite();
      instance.setMediaPacketFragment(value);
      return this;
    }
    /**
     * <code>.network.streamr.streamrvideo.data.model.proto.MediaPacketFragment mediaPacketFragment = 2;</code>
     */
    public Builder setMediaPacketFragment(
        network.streamr.streamrvideo.data.model.proto.MediaPacketFragment.Builder builderForValue) {
      copyOnWrite();
      instance.setMediaPacketFragment(builderForValue.build());
      return this;
    }
    /**
     * <code>.network.streamr.streamrvideo.data.model.proto.MediaPacketFragment mediaPacketFragment = 2;</code>
     */
    public Builder mergeMediaPacketFragment(network.streamr.streamrvideo.data.model.proto.MediaPacketFragment value) {
      copyOnWrite();
      instance.mergeMediaPacketFragment(value);
      return this;
    }
    /**
     * <code>.network.streamr.streamrvideo.data.model.proto.MediaPacketFragment mediaPacketFragment = 2;</code>
     */
    public Builder clearMediaPacketFragment() {
      copyOnWrite();
      instance.clearMediaPacketFragment();
      return this;
    }

    /**
     * <code>.network.streamr.streamrvideo.data.model.proto.Heartbeat heartbeat = 3;</code>
     */
    @java.lang.Override
    public boolean hasHeartbeat() {
      return instance.hasHeartbeat();
    }
    /**
     * <code>.network.streamr.streamrvideo.data.model.proto.Heartbeat heartbeat = 3;</code>
     */
    @java.lang.Override
    public network.streamr.streamrvideo.data.model.proto.Heartbeat getHeartbeat() {
      return instance.getHeartbeat();
    }
    /**
     * <code>.network.streamr.streamrvideo.data.model.proto.Heartbeat heartbeat = 3;</code>
     */
    public Builder setHeartbeat(network.streamr.streamrvideo.data.model.proto.Heartbeat value) {
      copyOnWrite();
      instance.setHeartbeat(value);
      return this;
    }
    /**
     * <code>.network.streamr.streamrvideo.data.model.proto.Heartbeat heartbeat = 3;</code>
     */
    public Builder setHeartbeat(
        network.streamr.streamrvideo.data.model.proto.Heartbeat.Builder builderForValue) {
      copyOnWrite();
      instance.setHeartbeat(builderForValue.build());
      return this;
    }
    /**
     * <code>.network.streamr.streamrvideo.data.model.proto.Heartbeat heartbeat = 3;</code>
     */
    public Builder mergeHeartbeat(network.streamr.streamrvideo.data.model.proto.Heartbeat value) {
      copyOnWrite();
      instance.mergeHeartbeat(value);
      return this;
    }
    /**
     * <code>.network.streamr.streamrvideo.data.model.proto.Heartbeat heartbeat = 3;</code>
     */
    public Builder clearHeartbeat() {
      copyOnWrite();
      instance.clearHeartbeat();
      return this;
    }

    /**
     * <code>.network.streamr.streamrvideo.data.model.proto.Leave leave = 4;</code>
     */
    @java.lang.Override
    public boolean hasLeave() {
      return instance.hasLeave();
    }
    /**
     * <code>.network.streamr.streamrvideo.data.model.proto.Leave leave = 4;</code>
     */
    @java.lang.Override
    public network.streamr.streamrvideo.data.model.proto.Leave getLeave() {
      return instance.getLeave();
    }
    /**
     * <code>.network.streamr.streamrvideo.data.model.proto.Leave leave = 4;</code>
     */
    public Builder setLeave(network.streamr.streamrvideo.data.model.proto.Leave value) {
      copyOnWrite();
      instance.setLeave(value);
      return this;
    }
    /**
     * <code>.network.streamr.streamrvideo.data.model.proto.Leave leave = 4;</code>
     */
    public Builder setLeave(
        network.streamr.streamrvideo.data.model.proto.Leave.Builder builderForValue) {
      copyOnWrite();
      instance.setLeave(builderForValue.build());
      return this;
    }
    /**
     * <code>.network.streamr.streamrvideo.data.model.proto.Leave leave = 4;</code>
     */
    public Builder mergeLeave(network.streamr.streamrvideo.data.model.proto.Leave value) {
      copyOnWrite();
      instance.mergeLeave(value);
      return this;
    }
    /**
     * <code>.network.streamr.streamrvideo.data.model.proto.Leave leave = 4;</code>
     */
    public Builder clearLeave() {
      copyOnWrite();
      instance.clearLeave();
      return this;
    }

    /**
     * <code>.network.streamr.streamrvideo.data.model.proto.ViewerInfo ViewerInfo = 5;</code>
     */
    @java.lang.Override
    public boolean hasViewerInfo() {
      return instance.hasViewerInfo();
    }
    /**
     * <code>.network.streamr.streamrvideo.data.model.proto.ViewerInfo ViewerInfo = 5;</code>
     */
    @java.lang.Override
    public network.streamr.streamrvideo.data.model.proto.ViewerInfo getViewerInfo() {
      return instance.getViewerInfo();
    }
    /**
     * <code>.network.streamr.streamrvideo.data.model.proto.ViewerInfo ViewerInfo = 5;</code>
     */
    public Builder setViewerInfo(network.streamr.streamrvideo.data.model.proto.ViewerInfo value) {
      copyOnWrite();
      instance.setViewerInfo(value);
      return this;
    }
    /**
     * <code>.network.streamr.streamrvideo.data.model.proto.ViewerInfo ViewerInfo = 5;</code>
     */
    public Builder setViewerInfo(
        network.streamr.streamrvideo.data.model.proto.ViewerInfo.Builder builderForValue) {
      copyOnWrite();
      instance.setViewerInfo(builderForValue.build());
      return this;
    }
    /**
     * <code>.network.streamr.streamrvideo.data.model.proto.ViewerInfo ViewerInfo = 5;</code>
     */
    public Builder mergeViewerInfo(network.streamr.streamrvideo.data.model.proto.ViewerInfo value) {
      copyOnWrite();
      instance.mergeViewerInfo(value);
      return this;
    }
    /**
     * <code>.network.streamr.streamrvideo.data.model.proto.ViewerInfo ViewerInfo = 5;</code>
     */
    public Builder clearViewerInfo() {
      copyOnWrite();
      instance.clearViewerInfo();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:network.streamr.streamrvideo.data.model.proto.Message)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new network.streamr.streamrvideo.data.model.proto.Message();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "body_",
            "bodyCase_",
            "messageId_",
            network.streamr.streamrvideo.data.model.proto.MediaPacketFragment.class,
            network.streamr.streamrvideo.data.model.proto.Heartbeat.class,
            network.streamr.streamrvideo.data.model.proto.Leave.class,
            network.streamr.streamrvideo.data.model.proto.ViewerInfo.class,
          };
          java.lang.String info =
              "\u0000\u0005\u0001\u0000\u0001\u0005\u0005\u0000\u0000\u0000\u0001\u0208\u0002<\u0000" +
              "\u0003<\u0000\u0004<\u0000\u0005<\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<network.streamr.streamrvideo.data.model.proto.Message> parser = PARSER;
        if (parser == null) {
          synchronized (network.streamr.streamrvideo.data.model.proto.Message.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<network.streamr.streamrvideo.data.model.proto.Message>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:network.streamr.streamrvideo.data.model.proto.Message)
  private static final network.streamr.streamrvideo.data.model.proto.Message DEFAULT_INSTANCE;
  static {
    Message defaultInstance = new Message();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      Message.class, defaultInstance);
  }

  public static network.streamr.streamrvideo.data.model.proto.Message getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Message> PARSER;

  public static com.google.protobuf.Parser<Message> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

