// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: media.proto
// Protobuf Java Version: 4.27.1

package network.streamr.streamrvideo.data.model.proto;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:network.streamr.streamrvideo.data.model.proto.Message)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string messageId = 1;</code>
   * @return The messageId.
   */
  java.lang.String getMessageId();
  /**
   * <code>string messageId = 1;</code>
   * @return The bytes for messageId.
   */
  com.google.protobuf.ByteString
      getMessageIdBytes();

  /**
   * <code>.network.streamr.streamrvideo.data.model.proto.MediaPacketFragment mediaPacketFragment = 2;</code>
   * @return Whether the mediaPacketFragment field is set.
   */
  boolean hasMediaPacketFragment();
  /**
   * <code>.network.streamr.streamrvideo.data.model.proto.MediaPacketFragment mediaPacketFragment = 2;</code>
   * @return The mediaPacketFragment.
   */
  network.streamr.streamrvideo.data.model.proto.MediaPacketFragment getMediaPacketFragment();

  /**
   * <code>.network.streamr.streamrvideo.data.model.proto.Heartbeat heartbeat = 3;</code>
   * @return Whether the heartbeat field is set.
   */
  boolean hasHeartbeat();
  /**
   * <code>.network.streamr.streamrvideo.data.model.proto.Heartbeat heartbeat = 3;</code>
   * @return The heartbeat.
   */
  network.streamr.streamrvideo.data.model.proto.Heartbeat getHeartbeat();

  /**
   * <code>.network.streamr.streamrvideo.data.model.proto.Leave leave = 4;</code>
   * @return Whether the leave field is set.
   */
  boolean hasLeave();
  /**
   * <code>.network.streamr.streamrvideo.data.model.proto.Leave leave = 4;</code>
   * @return The leave.
   */
  network.streamr.streamrvideo.data.model.proto.Leave getLeave();

  /**
   * <code>.network.streamr.streamrvideo.data.model.proto.ViewerInfo ViewerInfo = 5;</code>
   * @return Whether the viewerInfo field is set.
   */
  boolean hasViewerInfo();
  /**
   * <code>.network.streamr.streamrvideo.data.model.proto.ViewerInfo ViewerInfo = 5;</code>
   * @return The viewerInfo.
   */
  network.streamr.streamrvideo.data.model.proto.ViewerInfo getViewerInfo();

  public network.streamr.streamrvideo.data.model.proto.Message.BodyCase getBodyCase();
}
