// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: media.proto
// Protobuf Java Version: 4.27.1

package network.streamr.streamrvideo.data.model.proto;

/**
 * Protobuf type {@code network.streamr.streamrvideo.data.model.proto.VideoFrame}
 */
public  final class VideoFrame extends
    com.google.protobuf.GeneratedMessageLite<
        VideoFrame, VideoFrame.Builder> implements
    // @@protoc_insertion_point(message_implements:network.streamr.streamrvideo.data.model.proto.VideoFrame)
    VideoFrameOrBuilder {
  private VideoFrame() {
    data_ = com.google.protobuf.ByteString.EMPTY;
    extradata_ = com.google.protobuf.ByteString.EMPTY;
    codec_ = "";
  }
  public static final int FRAMENUMBER_FIELD_NUMBER = 1;
  private long frameNumber_;
  /**
   * <code>int64 frameNumber = 1;</code>
   * @return The frameNumber.
   */
  @java.lang.Override
  public long getFrameNumber() {
    return frameNumber_;
  }
  /**
   * <code>int64 frameNumber = 1;</code>
   * @param value The frameNumber to set.
   */
  private void setFrameNumber(long value) {
    
    frameNumber_ = value;
  }
  /**
   * <code>int64 frameNumber = 1;</code>
   */
  private void clearFrameNumber() {

    frameNumber_ = 0L;
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 2;
  private long timestamp_;
  /**
   * <code>int64 timestamp = 2;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public long getTimestamp() {
    return timestamp_;
  }
  /**
   * <code>int64 timestamp = 2;</code>
   * @param value The timestamp to set.
   */
  private void setTimestamp(long value) {
    
    timestamp_ = value;
  }
  /**
   * <code>int64 timestamp = 2;</code>
   */
  private void clearTimestamp() {

    timestamp_ = 0L;
  }

  public static final int DURATION_FIELD_NUMBER = 3;
  private long duration_;
  /**
   * <code>int64 duration = 3;</code>
   * @return The duration.
   */
  @java.lang.Override
  public long getDuration() {
    return duration_;
  }
  /**
   * <code>int64 duration = 3;</code>
   * @param value The duration to set.
   */
  private void setDuration(long value) {
    
    duration_ = value;
  }
  /**
   * <code>int64 duration = 3;</code>
   */
  private void clearDuration() {

    duration_ = 0L;
  }

  public static final int ISKEYFRAME_FIELD_NUMBER = 5;
  private boolean isKeyFrame_;
  /**
   * <code>bool isKeyFrame = 5;</code>
   * @return The isKeyFrame.
   */
  @java.lang.Override
  public boolean getIsKeyFrame() {
    return isKeyFrame_;
  }
  /**
   * <code>bool isKeyFrame = 5;</code>
   * @param value The isKeyFrame to set.
   */
  private void setIsKeyFrame(boolean value) {
    
    isKeyFrame_ = value;
  }
  /**
   * <code>bool isKeyFrame = 5;</code>
   */
  private void clearIsKeyFrame() {

    isKeyFrame_ = false;
  }

  public static final int SCREENORIENTATION_FIELD_NUMBER = 6;
  private int screenOrientation_;
  /**
   * <code>int32 screenOrientation = 6;</code>
   * @return The screenOrientation.
   */
  @java.lang.Override
  public int getScreenOrientation() {
    return screenOrientation_;
  }
  /**
   * <code>int32 screenOrientation = 6;</code>
   * @param value The screenOrientation to set.
   */
  private void setScreenOrientation(int value) {
    
    screenOrientation_ = value;
  }
  /**
   * <code>int32 screenOrientation = 6;</code>
   */
  private void clearScreenOrientation() {

    screenOrientation_ = 0;
  }

  public static final int DATA_FIELD_NUMBER = 7;
  private com.google.protobuf.ByteString data_;
  /**
   * <code>bytes data = 7;</code>
   * @return The data.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getData() {
    return data_;
  }
  /**
   * <code>bytes data = 7;</code>
   * @param value The data to set.
   */
  private void setData(com.google.protobuf.ByteString value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    data_ = value;
  }
  /**
   * <code>bytes data = 7;</code>
   */
  private void clearData() {

    data_ = getDefaultInstance().getData();
  }

  public static final int EXTRADATA_FIELD_NUMBER = 8;
  private com.google.protobuf.ByteString extradata_;
  /**
   * <code>bytes extradata = 8;</code>
   * @return The extradata.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getExtradata() {
    return extradata_;
  }
  /**
   * <code>bytes extradata = 8;</code>
   * @param value The extradata to set.
   */
  private void setExtradata(com.google.protobuf.ByteString value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    extradata_ = value;
  }
  /**
   * <code>bytes extradata = 8;</code>
   */
  private void clearExtradata() {

    extradata_ = getDefaultInstance().getExtradata();
  }

  public static final int CODEDWIDTH_FIELD_NUMBER = 9;
  private int codedWidth_;
  /**
   * <code>int32 codedWidth = 9;</code>
   * @return The codedWidth.
   */
  @java.lang.Override
  public int getCodedWidth() {
    return codedWidth_;
  }
  /**
   * <code>int32 codedWidth = 9;</code>
   * @param value The codedWidth to set.
   */
  private void setCodedWidth(int value) {
    
    codedWidth_ = value;
  }
  /**
   * <code>int32 codedWidth = 9;</code>
   */
  private void clearCodedWidth() {

    codedWidth_ = 0;
  }

  public static final int CODEDHEIGHT_FIELD_NUMBER = 10;
  private int codedHeight_;
  /**
   * <code>int32 codedHeight = 10;</code>
   * @return The codedHeight.
   */
  @java.lang.Override
  public int getCodedHeight() {
    return codedHeight_;
  }
  /**
   * <code>int32 codedHeight = 10;</code>
   * @param value The codedHeight to set.
   */
  private void setCodedHeight(int value) {
    
    codedHeight_ = value;
  }
  /**
   * <code>int32 codedHeight = 10;</code>
   */
  private void clearCodedHeight() {

    codedHeight_ = 0;
  }

  public static final int CODEC_FIELD_NUMBER = 11;
  private java.lang.String codec_;
  /**
   * <code>string codec = 11;</code>
   * @return The codec.
   */
  @java.lang.Override
  public java.lang.String getCodec() {
    return codec_;
  }
  /**
   * <code>string codec = 11;</code>
   * @return The bytes for codec.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCodecBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(codec_);
  }
  /**
   * <code>string codec = 11;</code>
   * @param value The codec to set.
   */
  private void setCodec(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    codec_ = value;
  }
  /**
   * <code>string codec = 11;</code>
   */
  private void clearCodec() {

    codec_ = getDefaultInstance().getCodec();
  }
  /**
   * <code>string codec = 11;</code>
   * @param value The bytes for codec to set.
   */
  private void setCodecBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    codec_ = value.toStringUtf8();

  }

  public static final int ISSCREENSHARING_FIELD_NUMBER = 12;
  private boolean isScreenSharing_;
  /**
   * <code>bool isScreenSharing = 12;</code>
   * @return The isScreenSharing.
   */
  @java.lang.Override
  public boolean getIsScreenSharing() {
    return isScreenSharing_;
  }
  /**
   * <code>bool isScreenSharing = 12;</code>
   * @param value The isScreenSharing to set.
   */
  private void setIsScreenSharing(boolean value) {
    
    isScreenSharing_ = value;
  }
  /**
   * <code>bool isScreenSharing = 12;</code>
   */
  private void clearIsScreenSharing() {

    isScreenSharing_ = false;
  }

  public static final int VIDEOORIENTATION_FIELD_NUMBER = 13;
  private int videoOrientation_;
  /**
   * <code>int32 videoOrientation = 13;</code>
   * @return The videoOrientation.
   */
  @java.lang.Override
  public int getVideoOrientation() {
    return videoOrientation_;
  }
  /**
   * <code>int32 videoOrientation = 13;</code>
   * @param value The videoOrientation to set.
   */
  private void setVideoOrientation(int value) {
    
    videoOrientation_ = value;
  }
  /**
   * <code>int32 videoOrientation = 13;</code>
   */
  private void clearVideoOrientation() {

    videoOrientation_ = 0;
  }

  public static network.streamr.streamrvideo.data.model.proto.VideoFrame parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static network.streamr.streamrvideo.data.model.proto.VideoFrame parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static network.streamr.streamrvideo.data.model.proto.VideoFrame parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static network.streamr.streamrvideo.data.model.proto.VideoFrame parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static network.streamr.streamrvideo.data.model.proto.VideoFrame parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static network.streamr.streamrvideo.data.model.proto.VideoFrame parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static network.streamr.streamrvideo.data.model.proto.VideoFrame parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static network.streamr.streamrvideo.data.model.proto.VideoFrame parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static network.streamr.streamrvideo.data.model.proto.VideoFrame parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static network.streamr.streamrvideo.data.model.proto.VideoFrame parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static network.streamr.streamrvideo.data.model.proto.VideoFrame parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static network.streamr.streamrvideo.data.model.proto.VideoFrame parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(network.streamr.streamrvideo.data.model.proto.VideoFrame prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code network.streamr.streamrvideo.data.model.proto.VideoFrame}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        network.streamr.streamrvideo.data.model.proto.VideoFrame, Builder> implements
      // @@protoc_insertion_point(builder_implements:network.streamr.streamrvideo.data.model.proto.VideoFrame)
      network.streamr.streamrvideo.data.model.proto.VideoFrameOrBuilder {
    // Construct using network.streamr.streamrvideo.data.model.proto.VideoFrame.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>int64 frameNumber = 1;</code>
     * @return The frameNumber.
     */
    @java.lang.Override
    public long getFrameNumber() {
      return instance.getFrameNumber();
    }
    /**
     * <code>int64 frameNumber = 1;</code>
     * @param value The frameNumber to set.
     * @return This builder for chaining.
     */
    public Builder setFrameNumber(long value) {
      copyOnWrite();
      instance.setFrameNumber(value);
      return this;
    }
    /**
     * <code>int64 frameNumber = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearFrameNumber() {
      copyOnWrite();
      instance.clearFrameNumber();
      return this;
    }

    /**
     * <code>int64 timestamp = 2;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return instance.getTimestamp();
    }
    /**
     * <code>int64 timestamp = 2;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(long value) {
      copyOnWrite();
      instance.setTimestamp(value);
      return this;
    }
    /**
     * <code>int64 timestamp = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      copyOnWrite();
      instance.clearTimestamp();
      return this;
    }

    /**
     * <code>int64 duration = 3;</code>
     * @return The duration.
     */
    @java.lang.Override
    public long getDuration() {
      return instance.getDuration();
    }
    /**
     * <code>int64 duration = 3;</code>
     * @param value The duration to set.
     * @return This builder for chaining.
     */
    public Builder setDuration(long value) {
      copyOnWrite();
      instance.setDuration(value);
      return this;
    }
    /**
     * <code>int64 duration = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearDuration() {
      copyOnWrite();
      instance.clearDuration();
      return this;
    }

    /**
     * <code>bool isKeyFrame = 5;</code>
     * @return The isKeyFrame.
     */
    @java.lang.Override
    public boolean getIsKeyFrame() {
      return instance.getIsKeyFrame();
    }
    /**
     * <code>bool isKeyFrame = 5;</code>
     * @param value The isKeyFrame to set.
     * @return This builder for chaining.
     */
    public Builder setIsKeyFrame(boolean value) {
      copyOnWrite();
      instance.setIsKeyFrame(value);
      return this;
    }
    /**
     * <code>bool isKeyFrame = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsKeyFrame() {
      copyOnWrite();
      instance.clearIsKeyFrame();
      return this;
    }

    /**
     * <code>int32 screenOrientation = 6;</code>
     * @return The screenOrientation.
     */
    @java.lang.Override
    public int getScreenOrientation() {
      return instance.getScreenOrientation();
    }
    /**
     * <code>int32 screenOrientation = 6;</code>
     * @param value The screenOrientation to set.
     * @return This builder for chaining.
     */
    public Builder setScreenOrientation(int value) {
      copyOnWrite();
      instance.setScreenOrientation(value);
      return this;
    }
    /**
     * <code>int32 screenOrientation = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearScreenOrientation() {
      copyOnWrite();
      instance.clearScreenOrientation();
      return this;
    }

    /**
     * <code>bytes data = 7;</code>
     * @return The data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getData() {
      return instance.getData();
    }
    /**
     * <code>bytes data = 7;</code>
     * @param value The data to set.
     * @return This builder for chaining.
     */
    public Builder setData(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setData(value);
      return this;
    }
    /**
     * <code>bytes data = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearData() {
      copyOnWrite();
      instance.clearData();
      return this;
    }

    /**
     * <code>bytes extradata = 8;</code>
     * @return The extradata.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getExtradata() {
      return instance.getExtradata();
    }
    /**
     * <code>bytes extradata = 8;</code>
     * @param value The extradata to set.
     * @return This builder for chaining.
     */
    public Builder setExtradata(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setExtradata(value);
      return this;
    }
    /**
     * <code>bytes extradata = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearExtradata() {
      copyOnWrite();
      instance.clearExtradata();
      return this;
    }

    /**
     * <code>int32 codedWidth = 9;</code>
     * @return The codedWidth.
     */
    @java.lang.Override
    public int getCodedWidth() {
      return instance.getCodedWidth();
    }
    /**
     * <code>int32 codedWidth = 9;</code>
     * @param value The codedWidth to set.
     * @return This builder for chaining.
     */
    public Builder setCodedWidth(int value) {
      copyOnWrite();
      instance.setCodedWidth(value);
      return this;
    }
    /**
     * <code>int32 codedWidth = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearCodedWidth() {
      copyOnWrite();
      instance.clearCodedWidth();
      return this;
    }

    /**
     * <code>int32 codedHeight = 10;</code>
     * @return The codedHeight.
     */
    @java.lang.Override
    public int getCodedHeight() {
      return instance.getCodedHeight();
    }
    /**
     * <code>int32 codedHeight = 10;</code>
     * @param value The codedHeight to set.
     * @return This builder for chaining.
     */
    public Builder setCodedHeight(int value) {
      copyOnWrite();
      instance.setCodedHeight(value);
      return this;
    }
    /**
     * <code>int32 codedHeight = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearCodedHeight() {
      copyOnWrite();
      instance.clearCodedHeight();
      return this;
    }

    /**
     * <code>string codec = 11;</code>
     * @return The codec.
     */
    @java.lang.Override
    public java.lang.String getCodec() {
      return instance.getCodec();
    }
    /**
     * <code>string codec = 11;</code>
     * @return The bytes for codec.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCodecBytes() {
      return instance.getCodecBytes();
    }
    /**
     * <code>string codec = 11;</code>
     * @param value The codec to set.
     * @return This builder for chaining.
     */
    public Builder setCodec(
        java.lang.String value) {
      copyOnWrite();
      instance.setCodec(value);
      return this;
    }
    /**
     * <code>string codec = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearCodec() {
      copyOnWrite();
      instance.clearCodec();
      return this;
    }
    /**
     * <code>string codec = 11;</code>
     * @param value The bytes for codec to set.
     * @return This builder for chaining.
     */
    public Builder setCodecBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setCodecBytes(value);
      return this;
    }

    /**
     * <code>bool isScreenSharing = 12;</code>
     * @return The isScreenSharing.
     */
    @java.lang.Override
    public boolean getIsScreenSharing() {
      return instance.getIsScreenSharing();
    }
    /**
     * <code>bool isScreenSharing = 12;</code>
     * @param value The isScreenSharing to set.
     * @return This builder for chaining.
     */
    public Builder setIsScreenSharing(boolean value) {
      copyOnWrite();
      instance.setIsScreenSharing(value);
      return this;
    }
    /**
     * <code>bool isScreenSharing = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsScreenSharing() {
      copyOnWrite();
      instance.clearIsScreenSharing();
      return this;
    }

    /**
     * <code>int32 videoOrientation = 13;</code>
     * @return The videoOrientation.
     */
    @java.lang.Override
    public int getVideoOrientation() {
      return instance.getVideoOrientation();
    }
    /**
     * <code>int32 videoOrientation = 13;</code>
     * @param value The videoOrientation to set.
     * @return This builder for chaining.
     */
    public Builder setVideoOrientation(int value) {
      copyOnWrite();
      instance.setVideoOrientation(value);
      return this;
    }
    /**
     * <code>int32 videoOrientation = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearVideoOrientation() {
      copyOnWrite();
      instance.clearVideoOrientation();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:network.streamr.streamrvideo.data.model.proto.VideoFrame)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new network.streamr.streamrvideo.data.model.proto.VideoFrame();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "frameNumber_",
            "timestamp_",
            "duration_",
            "isKeyFrame_",
            "screenOrientation_",
            "data_",
            "extradata_",
            "codedWidth_",
            "codedHeight_",
            "codec_",
            "isScreenSharing_",
            "videoOrientation_",
          };
          java.lang.String info =
              "\u0000\f\u0000\u0000\u0001\r\f\u0000\u0000\u0000\u0001\u0002\u0002\u0002\u0003\u0002" +
              "\u0005\u0007\u0006\u0004\u0007\n\b\n\t\u0004\n\u0004\u000b\u0208\f\u0007\r\u0004" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<network.streamr.streamrvideo.data.model.proto.VideoFrame> parser = PARSER;
        if (parser == null) {
          synchronized (network.streamr.streamrvideo.data.model.proto.VideoFrame.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<network.streamr.streamrvideo.data.model.proto.VideoFrame>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:network.streamr.streamrvideo.data.model.proto.VideoFrame)
  private static final network.streamr.streamrvideo.data.model.proto.VideoFrame DEFAULT_INSTANCE;
  static {
    VideoFrame defaultInstance = new VideoFrame();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      VideoFrame.class, defaultInstance);
  }

  public static network.streamr.streamrvideo.data.model.proto.VideoFrame getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<VideoFrame> PARSER;

  public static com.google.protobuf.Parser<VideoFrame> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

