// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: media.proto
// Protobuf Java Version: 4.27.1

package network.streamr.streamrvideo.data.model.proto;

public interface VideoFrameOrBuilder extends
    // @@protoc_insertion_point(interface_extends:network.streamr.streamrvideo.data.model.proto.VideoFrame)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>int64 frameNumber = 1;</code>
   * @return The frameNumber.
   */
  long getFrameNumber();

  /**
   * <code>int64 timestamp = 2;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <code>int64 duration = 3;</code>
   * @return The duration.
   */
  long getDuration();

  /**
   * <code>bool isKeyFrame = 5;</code>
   * @return The isKeyFrame.
   */
  boolean getIsKeyFrame();

  /**
   * <code>int32 screenOrientation = 6;</code>
   * @return The screenOrientation.
   */
  int getScreenOrientation();

  /**
   * <code>bytes data = 7;</code>
   * @return The data.
   */
  com.google.protobuf.ByteString getData();

  /**
   * <code>bytes extradata = 8;</code>
   * @return The extradata.
   */
  com.google.protobuf.ByteString getExtradata();

  /**
   * <code>int32 codedWidth = 9;</code>
   * @return The codedWidth.
   */
  int getCodedWidth();

  /**
   * <code>int32 codedHeight = 10;</code>
   * @return The codedHeight.
   */
  int getCodedHeight();

  /**
   * <code>string codec = 11;</code>
   * @return The codec.
   */
  java.lang.String getCodec();
  /**
   * <code>string codec = 11;</code>
   * @return The bytes for codec.
   */
  com.google.protobuf.ByteString
      getCodecBytes();

  /**
   * <code>bool isScreenSharing = 12;</code>
   * @return The isScreenSharing.
   */
  boolean getIsScreenSharing();

  /**
   * <code>int32 videoOrientation = 13;</code>
   * @return The videoOrientation.
   */
  int getVideoOrientation();
}
