// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: media.proto
// Protobuf Java Version: 4.27.1

package network.streamr.streamrvideo.data.model.proto;

/**
 * Protobuf type {@code network.streamr.streamrvideo.data.model.proto.ViewerInfo}
 */
public  final class ViewerInfo extends
    com.google.protobuf.GeneratedMessageLite<
        ViewerInfo, ViewerInfo.Builder> implements
    // @@protoc_insertion_point(message_implements:network.streamr.streamrvideo.data.model.proto.ViewerInfo)
    ViewerInfoOrBuilder {
  private ViewerInfo() {
  }
  public static final int VIEWERCOUNT_FIELD_NUMBER = 1;
  private int viewerCount_;
  /**
   * <code>int32 viewerCount = 1;</code>
   * @return The viewerCount.
   */
  @java.lang.Override
  public int getViewerCount() {
    return viewerCount_;
  }
  /**
   * <code>int32 viewerCount = 1;</code>
   * @param value The viewerCount to set.
   */
  private void setViewerCount(int value) {
    
    viewerCount_ = value;
  }
  /**
   * <code>int32 viewerCount = 1;</code>
   */
  private void clearViewerCount() {

    viewerCount_ = 0;
  }

  public static network.streamr.streamrvideo.data.model.proto.ViewerInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static network.streamr.streamrvideo.data.model.proto.ViewerInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static network.streamr.streamrvideo.data.model.proto.ViewerInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static network.streamr.streamrvideo.data.model.proto.ViewerInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static network.streamr.streamrvideo.data.model.proto.ViewerInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static network.streamr.streamrvideo.data.model.proto.ViewerInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static network.streamr.streamrvideo.data.model.proto.ViewerInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static network.streamr.streamrvideo.data.model.proto.ViewerInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static network.streamr.streamrvideo.data.model.proto.ViewerInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static network.streamr.streamrvideo.data.model.proto.ViewerInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static network.streamr.streamrvideo.data.model.proto.ViewerInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static network.streamr.streamrvideo.data.model.proto.ViewerInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(network.streamr.streamrvideo.data.model.proto.ViewerInfo prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code network.streamr.streamrvideo.data.model.proto.ViewerInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        network.streamr.streamrvideo.data.model.proto.ViewerInfo, Builder> implements
      // @@protoc_insertion_point(builder_implements:network.streamr.streamrvideo.data.model.proto.ViewerInfo)
      network.streamr.streamrvideo.data.model.proto.ViewerInfoOrBuilder {
    // Construct using network.streamr.streamrvideo.data.model.proto.ViewerInfo.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>int32 viewerCount = 1;</code>
     * @return The viewerCount.
     */
    @java.lang.Override
    public int getViewerCount() {
      return instance.getViewerCount();
    }
    /**
     * <code>int32 viewerCount = 1;</code>
     * @param value The viewerCount to set.
     * @return This builder for chaining.
     */
    public Builder setViewerCount(int value) {
      copyOnWrite();
      instance.setViewerCount(value);
      return this;
    }
    /**
     * <code>int32 viewerCount = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearViewerCount() {
      copyOnWrite();
      instance.clearViewerCount();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:network.streamr.streamrvideo.data.model.proto.ViewerInfo)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new network.streamr.streamrvideo.data.model.proto.ViewerInfo();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "viewerCount_",
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0004";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<network.streamr.streamrvideo.data.model.proto.ViewerInfo> parser = PARSER;
        if (parser == null) {
          synchronized (network.streamr.streamrvideo.data.model.proto.ViewerInfo.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<network.streamr.streamrvideo.data.model.proto.ViewerInfo>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:network.streamr.streamrvideo.data.model.proto.ViewerInfo)
  private static final network.streamr.streamrvideo.data.model.proto.ViewerInfo DEFAULT_INSTANCE;
  static {
    ViewerInfo defaultInstance = new ViewerInfo();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      ViewerInfo.class, defaultInstance);
  }

  public static network.streamr.streamrvideo.data.model.proto.ViewerInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ViewerInfo> PARSER;

  public static com.google.protobuf.Parser<ViewerInfo> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

