name: Android Release StreamrProxyClient
on:
  release:
    types: [published]
env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
jobs:
  build-android:
    runs-on: macos-13
    env:
      ARCHFLAGS: --android
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android NDK
        run: |
          echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "ndk;27.1.12297006"
          echo "ANDROID_NDK_HOME=$ANDROID_HOME/ndk/27.1.12297006" >> $GITHUB_ENV

      - name: Verify NDK
        run: |
          echo "NDK Home: $ANDROID_NDK_HOME"
          ls -l $ANDROID_NDK_HOME
          cat $ANDROID_NDK_HOME/source.properties
          
      - name: Install Dependencies
        uses: ./.github/workflows/reusable/cached-install
