name: Release StreamrProxyClient

on:
  release:
    types: [published]

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  build-desktop:
    strategy:
      matrix:
        include:
          - os: macos-14
            target: arm64-osx
          - os: macos-13
            target: x64-osx
          - os: ubuntu-24.04
            target: x64-linux
          - os: linux-arm64-runner
            target: arm64-linux
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Dependencies
        uses: ./.github/workflows/reusable/cached-install
      
      - name: test
        run:
          ./test.sh
        shell: bash
      
      - name: Package and Upload
        run: |
          # Only package the compiled libraries
          cd ./packages/streamr-libstreamrproxyclient/dist
          tar -czf streamrproxyclient-${{ matrix.target }}.tgz ${{ matrix.target }}
          gh release upload ${{ github.event.release.tag_name }} streamrproxyclient-${{ matrix.target }}.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-ios:
    needs: build-desktop
    runs-on: macos-14
    env:
      ARCHFLAGS: --ios
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Dependencies
        uses: ./.github/workflows/reusable/cached-install
        
      - name: Package and Upload
        run: |
          cd ./packages/streamr-libstreamrproxyclient/dist/ios-swift-package
          tar -czhf streamrproxyclient-ios-swift-package.tgz --exclude-from=StreamrProxyClient/.gitignore StreamrProxyClient
          gh release upload ${{ github.event.release.tag_name }} streamrproxyclient-ios-swift-package.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-android:
    needs: build-desktop
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: Install Android NDK
        run: |
          echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "ndk;27.1.12297006"
          echo "ANDROID_NDK_HOME=$ANDROID_HOME/ndk/27.1.12297006" >> $GITHUB_ENV
      - name: Verify NDK
        run: |
          echo "NDK Home: $ANDROID_NDK_HOME"
          ls -l $ANDROID_NDK_HOME
          cat $ANDROID_NDK_HOME/source.properties
      - name: Install Dependencies
        uses: ./.github/workflows/reusable/cached-install
        env:
          ANDROID_NDK_HOME: ${{ env.ANDROID_NDK_HOME }}
          ANDROID_NDK: ${{ env.ANDROID_NDK_HOME }}
          NDK_HOME: ${{ env.ANDROID_NDK_HOME }}
      - name: Package and Upload
        run: |
          cd ./packages/streamr-libstreamrproxyclient/dist/android-library-module
          tar -czhf streamrproxyclient-android-library-module.tgz --exclude-from=StreamrProxyClient/.gitignore StreamrProxyClient
          gh release upload ${{ github.event.release.tag_name }} streamrproxyclient-android-library-module.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  verify-release:
    needs: [build-desktop, build-ios, build-android]
    runs-on: ubuntu-latest
    steps:
      - name: Verify Release Artifacts
        run: |
          gh release view ${{ github.event.release.tag_name }} --json assets -q '.assets[].name' | grep -E 'streamrproxyclient-((arm64|x64)-(osx|linux)|ios-swift-package|android-library-module).tgz'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  

