name: Release StreamrProxyClient

on:
  release:
    types: [published]

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  build-android:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
          
      - name: Install Dependencies
        uses: ./.github/workflows/reusable/cached-install
        env:
          ANDROID_NDK_HOME: ${{ env.ANDROID_NDK_HOME }}
          ANDROID_NDK: ${{ env.ANDROID_NDK_HOME }}
          NDK_HOME: ${{ env.ANDROID_NDK_HOME }}
          
      - name: Package and Upload
        run: |
          cd ./packages/streamr-libstreamrproxyclient/dist
          gh release upload ${{ github.event.release.tag_name }} android-library-module/streamrproxyclient-android-library-module-*.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
