name: validate iOS

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  ARCHFLAGS: --ios

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  install-lint:
    if: contains(github.event.head_commit.message, 'iosbuild')
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: install
        uses: ./.github/workflows/reusable/cached-install
