name: validate Android 

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  ARCHFLAGS: --android

on:
  push:
    branches:
      - '*' 
  pull_request:
    branches:
      - '*'

jobs:
  install-lint:
    if: contains(github.event.head_commit.message, 'androidbuild')
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: '27.1.12297006'
      - name: Verify NDK Setup
        run: |
          echo "ANDROID_NDK_HOME: $ANDROID_NDK_HOME"
          echo "NDK Version:"
          cat $ANDROID_NDK_HOME/source.properties
        shell: bash
      - name: install
        uses: ./.github/workflows/reusable/cached-install
      - name: lint
        run:
          ./lint.sh
        shell: bash
