name: validate Android 

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  ARCHFLAGS: --android

on:
  push:
    branches:
      - '*' 
  pull_request:
    branches:
      - '*'

jobs:
  install-lint:
    if: contains(github.event.head_commit.message, 'androidbuild')
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: install
        uses: ./.github/workflows/reusable/cached-install
      - name: lint
        run:
          ./lint.sh
        shell: bash
